(function(a,b,c){function d(a,c){this.wrapper="string"==typeof a?b.querySelector(a):a;this.scroller=this.wrapper.children[0];this.scrollerStyle=this.scroller.style;this.options={resizeScrollbars:!0,mouseWheelSpeed:20,snapThreshold:.334,startX:0,startY:0,scrollY:!0,directionLockThreshold:5,momentum:!0,bounce:!0,bounceTime:600,bounceEasing:"",preventDefault:!0,preventDefaultException:{tagName:/^(INPUT|TEXTAREA|BUTTON|SELECT)$/},HWCompositing:!0,useTransition:!0,useTransform:!0};for(var d in c)this.options[d]=
c[d];this.translateZ=this.options.HWCompositing&&k.hasPerspective?" translateZ(0)":"";this.options.useTransition=k.hasTransition&&this.options.useTransition;this.options.useTransform=k.hasTransform&&this.options.useTransform;this.options.eventPassthrough=!0===this.options.eventPassthrough?"vertical":this.options.eventPassthrough;this.options.preventDefault=!this.options.eventPassthrough&&this.options.preventDefault;this.options.scrollY="vertical"==this.options.eventPassthrough?!1:this.options.scrollY;
this.options.scrollX="horizontal"==this.options.eventPassthrough?!1:this.options.scrollX;this.options.freeScroll=this.options.freeScroll&&!this.options.eventPassthrough;this.options.directionLockThreshold=this.options.eventPassthrough?0:this.options.directionLockThreshold;this.options.bounceEasing="string"==typeof this.options.bounceEasing?k.ease[this.options.bounceEasing]||k.ease.circular:this.options.bounceEasing;this.options.resizePolling=void 0===this.options.resizePolling?60:this.options.resizePolling;
!0===this.options.tap&&(this.options.tap="tap");"scale"==this.options.shrinkScrollbars&&(this.options.useTransition=!1);this.options.invertWheelDirection=this.options.invertWheelDirection?-1:1;this.directionY=this.directionX=this.y=this.x=0;this._events={};this._init();this.refresh();this.scrollTo(this.options.startX,this.options.startY);this.enable()}function g(a,c,d){var g=b.createElement("div"),h=b.createElement("div");!0===d&&(g.style.cssText="position:absolute;z-index:9999",h.style.cssText="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;position:absolute;background:rgba(0,0,0,0.5);border:1px solid rgba(255,255,255,0.9);border-radius:3px");
h.className="iScrollIndicator";"h"==a?(!0===d&&(g.style.cssText+=";height:7px;left:2px;right:2px;bottom:0",h.style.height="100%"),g.className="iScrollHorizontalScrollbar"):(!0===d&&(g.style.cssText+=";width:7px;bottom:2px;top:2px;right:1px",h.style.width="100%"),g.className="iScrollVerticalScrollbar");g.style.cssText+=";overflow:hidden";c||(g.style.pointerEvents="none");g.appendChild(h);return g}function l(m,c){this.wrapper="string"==typeof c.el?b.querySelector(c.el):c.el;this.wrapperStyle=this.wrapper.style;
this.indicator=this.wrapper.children[0];this.indicatorStyle=this.indicator.style;this.scroller=m;this.options={listenX:!0,listenY:!0,interactive:!1,resize:!0,defaultScrollbars:!1,shrink:!1,fade:!1,speedRatioX:0,speedRatioY:0};for(var d in c)this.options[d]=c[d];this.sizeRatioY=this.sizeRatioX=1;this.maxPosY=this.maxPosX=0;this.options.interactive&&(this.options.disableTouch||(k.addEvent(this.indicator,"touchstart",this),k.addEvent(a,"touchend",this)),this.options.disablePointer||(k.addEvent(this.indicator,
k.prefixPointerEvent("pointerdown"),this),k.addEvent(a,k.prefixPointerEvent("pointerup"),this)),this.options.disableMouse||(k.addEvent(this.indicator,"mousedown",this),k.addEvent(a,"mouseup",this)));this.options.fade&&(this.wrapperStyle[k.style.transform]=this.scroller.translateZ,this.wrapperStyle[k.style.transitionDuration]=k.isBadAndroid?"0.001s":"0ms",this.wrapperStyle.opacity="0")}var h=a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||
a.msRequestAnimationFrame||function(m){a.setTimeout(m,1E3/60)},k=function(){function m(a){return!1===h?!1:""===h?a:h+a.charAt(0).toUpperCase()+a.substr(1)}var d={},g=b.createElement("div").style,h=function(){for(var a=["t","webkitT","MozT","msT","OT"],m,b=0,c=a.length;b<c;b++)if(m=a[b]+"ransform",m in g)return a[b].substr(0,a[b].length-1);return!1}();d.getTime=Date.now||function(){return(new Date).getTime()};d.extend=function(a,m){for(var b in m)a[b]=m[b]};d.addEvent=function(a,m,b,c){a.addEventListener(m,
b,!!c)};d.removeEvent=function(a,m,b,c){a.removeEventListener(m,b,!!c)};d.prefixPointerEvent=function(m){return a.MSPointerEvent?"MSPointer"+m.charAt(9).toUpperCase()+m.substr(10):m};d.momentum=function(a,m,b,d,g,h){m=a-m;b=c.abs(m)/b;var n;h=void 0===h?6E-4:h;n=a+b*b/(2*h)*(0>m?-1:1);h=b/h;n<d?(n=g?d-g/2.5*(b/8):d,m=c.abs(n-a),h=m/b):0<n&&(n=g?g/2.5*(b/8):0,m=c.abs(a)+n,h=m/b);return{destination:c.round(n),duration:h}};var k=m("transform");d.extend(d,{hasTransform:!1!==k,hasPerspective:m("perspective")in
g,hasTouch:"ontouchstart"in a,hasPointer:a.PointerEvent||a.MSPointerEvent,hasTransition:m("transition")in g});d.isBadAndroid=/Android /.test(a.navigator.appVersion)&&!/Chrome\/\d/.test(a.navigator.appVersion);d.extend(d.style={},{transform:k,transitionTimingFunction:m("transitionTimingFunction"),transitionDuration:m("transitionDuration"),transitionDelay:m("transitionDelay"),transformOrigin:m("transformOrigin")});d.hasClass=function(a,m){return(new RegExp("(^|\\s)"+m+"(\\s|$)")).test(a.className)};
d.addClass=function(a,m){if(!d.hasClass(a,m)){var b=a.className.split(" ");b.push(m);a.className=b.join(" ")}};d.removeClass=function(a,m){d.hasClass(a,m)&&(a.className=a.className.replace(new RegExp("(^|\\s)"+m+"(\\s|$)","g")," "))};d.offset=function(a){for(var m=-a.offsetLeft,b=-a.offsetTop;a=a.offsetParent;)m-=a.offsetLeft,b-=a.offsetTop;return{left:m,top:b}};d.preventDefaultException=function(a,m){for(var b in m)if(m[b].test(a[b]))return!0;return!1};d.extend(d.eventType={},{touchstart:1,touchmove:1,
touchend:1,mousedown:2,mousemove:2,mouseup:2,pointerdown:3,pointermove:3,pointerup:3,MSPointerDown:3,MSPointerMove:3,MSPointerUp:3});d.extend(d.ease={},{quadratic:{style:"cubic-bezier(0.25, 0.46, 0.45, 0.94)",fn:function(a){return a*(2-a)}},circular:{style:"cubic-bezier(0.1, 0.57, 0.1, 1)",fn:function(a){return c.sqrt(1- --a*a)}},back:{style:"cubic-bezier(0.175, 0.885, 0.32, 1.275)",fn:function(a){return--a*a*(5*a+4)+1}},bounce:{style:"",fn:function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*
(a-=1.5/2.75)*a+.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+.9375:7.5625*(a-=2.625/2.75)*a+.984375}},elastic:{style:"",fn:function(a){return 0===a?0:1==a?1:.4*c.pow(2,-10*a)*c.sin(2*(a-.055)*c.PI/.22)+1}}});d.tap=function(a,m){var c=b.createEvent("Event");c.initEvent(m,!0,!0);c.pageX=a.pageX;c.pageY=a.pageY;a.target.dispatchEvent(c)};d.click=function(a){var m=a.target,c;/(SELECT|INPUT|TEXTAREA)/i.test(m.tagName)||(c=b.createEvent("MouseEvents"),c.initMouseEvent("click",!0,!0,a.view,1,m.screenX,m.screenY,
m.clientX,m.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,null),c._constructed=!0,m.dispatchEvent(c))};return d}();d.prototype={version:"5.1.3",_init:function(){this._initEvents();(this.options.scrollbars||this.options.indicators)&&this._initIndicators();this.options.mouseWheel&&this._initWheel();this.options.snap&&this._initSnap();this.options.keyBindings&&this._initKeys()},destroy:function(){this._initEvents(!0);this._execEvent("destroy")},_transitionEnd:function(a){a.target==this.scroller&&
this.isInTransition&&(this._transitionTime(),this.resetPosition(this.options.bounceTime)||(this.isInTransition=!1,this._execEvent("scrollEnd")))},_start:function(a){if(!(1!=k.eventType[a.type]&&0!==a.button||!this.enabled||this.initiated&&k.eventType[a.type]!==this.initiated)){!this.options.preventDefault||k.isBadAndroid||k.preventDefaultException(a.target,this.options.preventDefaultException)||a.preventDefault();var b=a.touches?a.touches[0]:a;this.initiated=k.eventType[a.type];this.moved=!1;this.directionLocked=
this.directionY=this.directionX=this.distY=this.distX=0;this._transitionTime();this.startTime=k.getTime();this.options.useTransition&&this.isInTransition?(this.isInTransition=!1,a=this.getComputedPosition(),this._translate(c.round(a.x),c.round(a.y)),this._execEvent("scrollEnd")):!this.options.useTransition&&this.isAnimating&&(this.isAnimating=!1,this._execEvent("scrollEnd"));this.startX=this.x;this.startY=this.y;this.absStartX=this.x;this.absStartY=this.y;this.pointX=b.pageX;this.pointY=b.pageY;this._execEvent("beforeScrollStart")}},
_move:function(a){if(this.enabled&&k.eventType[a.type]===this.initiated){this.options.preventDefault&&a.preventDefault();var b=a.touches?a.touches[0]:a,d=b.pageX-this.pointX,g=b.pageY-this.pointY,h=k.getTime(),l;this.pointX=b.pageX;this.pointY=b.pageY;this.distX+=d;this.distY+=g;b=c.abs(this.distX);l=c.abs(this.distY);if(!(300<h-this.endTime&&10>b&&10>l)){this.directionLocked||this.options.freeScroll||(this.directionLocked=b>l+this.options.directionLockThreshold?"h":l>=b+this.options.directionLockThreshold?
"v":"n");if("h"==this.directionLocked){if("vertical"==this.options.eventPassthrough)a.preventDefault();else if("horizontal"==this.options.eventPassthrough){this.initiated=!1;return}g=0}else if("v"==this.directionLocked){if("horizontal"==this.options.eventPassthrough)a.preventDefault();else if("vertical"==this.options.eventPassthrough){this.initiated=!1;return}d=0}d=this.hasHorizontalScroll?d:0;g=this.hasVerticalScroll?g:0;a=this.x+d;b=this.y+g;if(0<a||a<this.maxScrollX)a=this.options.bounce?this.x+
d/3:0<a?0:this.maxScrollX;if(0<b||b<this.maxScrollY)b=this.options.bounce?this.y+g/3:0<b?0:this.maxScrollY;this.directionX=0<d?-1:0>d?1:0;this.directionY=0<g?-1:0>g?1:0;this.moved||this._execEvent("scrollStart");this.moved=!0;this._translate(a,b);300<h-this.startTime&&(this.startTime=h,this.startX=this.x,this.startY=this.y)}}},_end:function(a){if(this.enabled&&k.eventType[a.type]===this.initiated){this.options.preventDefault&&!k.preventDefaultException(a.target,this.options.preventDefaultException)&&
a.preventDefault();var b,d;d=k.getTime()-this.startTime;var g=c.round(this.x),h=c.round(this.y),l=c.abs(g-this.startX),w=c.abs(h-this.startY);b=0;var p="";this.initiated=this.isInTransition=0;this.endTime=k.getTime();if(!this.resetPosition(this.options.bounceTime))if(this.scrollTo(g,h),this.moved)if(this._events.flick&&200>d&&100>l&&100>w)this._execEvent("flick");else if(this.options.momentum&&300>d&&(b=this.hasHorizontalScroll?k.momentum(this.x,this.startX,d,this.maxScrollX,this.options.bounce?this.wrapperWidth:
0,this.options.deceleration):{destination:g,duration:0},d=this.hasVerticalScroll?k.momentum(this.y,this.startY,d,this.maxScrollY,this.options.bounce?this.wrapperHeight:0,this.options.deceleration):{destination:h,duration:0},g=b.destination,h=d.destination,b=c.max(b.duration,d.duration),this.isInTransition=1),this.options.snap&&(this.currentPage=p=this._nearestSnap(g,h),b=this.options.snapSpeed||c.max(c.max(c.min(c.abs(g-p.x),1E3),c.min(c.abs(h-p.y),1E3)),300),g=p.x,h=p.y,this.directionY=this.directionX=
0,p=this.options.bounceEasing),g!=this.x||h!=this.y){if(0<g||g<this.maxScrollX||0<h||h<this.maxScrollY)p=k.ease.quadratic;this.scrollTo(g,h,b,p)}else this._execEvent("scrollEnd");else this.options.tap&&k.tap(a,this.options.tap),this.options.click&&k.click(a),this._execEvent("scrollCancel")}},_resize:function(){var a=this;clearTimeout(this.resizeTimeout);this.resizeTimeout=setTimeout(function(){a.refresh()},this.options.resizePolling)},resetPosition:function(a){var b=this.x,c=this.y;!this.hasHorizontalScroll||
0<this.x?b=0:this.x<this.maxScrollX&&(b=this.maxScrollX);!this.hasVerticalScroll||0<this.y?c=0:this.y<this.maxScrollY&&(c=this.maxScrollY);if(b==this.x&&c==this.y)return!1;this.scrollTo(b,c,a||0,this.options.bounceEasing);return!0},disable:function(){this.enabled=!1},enable:function(){this.enabled=!0},refresh:function(){this.wrapperWidth=this.wrapper.clientWidth;this.wrapperHeight=this.wrapper.clientHeight;this.scrollerWidth=this.scroller.offsetWidth;this.scrollerHeight=this.scroller.offsetHeight;
this.maxScrollX=this.wrapperWidth-this.scrollerWidth;this.maxScrollY=this.wrapperHeight-this.scrollerHeight;this.hasHorizontalScroll=this.options.scrollX&&0>this.maxScrollX;this.hasVerticalScroll=this.options.scrollY&&0>this.maxScrollY;this.hasHorizontalScroll||(this.maxScrollX=0,this.scrollerWidth=this.wrapperWidth);this.hasVerticalScroll||(this.maxScrollY=0,this.scrollerHeight=this.wrapperHeight);this.directionY=this.directionX=this.endTime=0;this.wrapperOffset=k.offset(this.wrapper);this._execEvent("refresh");
this.resetPosition()},on:function(a,b){this._events[a]||(this._events[a]=[]);this._events[a].push(b)},off:function(a,b){if(this._events[a]){var c=this._events[a].indexOf(b);-1<c&&this._events[a].splice(c,1)}},_execEvent:function(a){if(this._events[a]){var b=0,c=this._events[a].length;if(c)for(;b<c;b++)this._events[a][b].apply(this,[].slice.call(arguments,1))}},scrollBy:function(a,b,c,d){a=this.x+a;b=this.y+b;this.scrollTo(a,b,c||0,d)},scrollTo:function(a,b,c,d){d=d||k.ease.circular;this.isInTransition=
this.options.useTransition&&0<c;!c||this.options.useTransition&&d.style?(this._transitionTimingFunction(d.style),this._transitionTime(c),this._translate(a,b)):this._animate(a,b,c,d.fn)},scrollToElement:function(a,b,d,g,h){if(a=a.nodeType?a:this.scroller.querySelector(a)){var l=k.offset(a);l.left-=this.wrapperOffset.left;l.top-=this.wrapperOffset.top;!0===d&&(d=c.round(a.offsetWidth/2-this.wrapper.offsetWidth/2));!0===g&&(g=c.round(a.offsetHeight/2-this.wrapper.offsetHeight/2));l.left-=d||0;l.top-=
g||0;l.left=0<l.left?0:l.left<this.maxScrollX?this.maxScrollX:l.left;l.top=0<l.top?0:l.top<this.maxScrollY?this.maxScrollY:l.top;b=void 0===b||null===b||"auto"===b?c.max(c.abs(this.x-l.left),c.abs(this.y-l.top)):b;this.scrollTo(l.left,l.top,b,h)}},_transitionTime:function(a){a=a||0;this.scrollerStyle[k.style.transitionDuration]=a+"ms";!a&&k.isBadAndroid&&(this.scrollerStyle[k.style.transitionDuration]="0.001s");if(this.indicators)for(var b=this.indicators.length;b--;)this.indicators[b].transitionTime(a)},
_transitionTimingFunction:function(a){this.scrollerStyle[k.style.transitionTimingFunction]=a;if(this.indicators)for(var b=this.indicators.length;b--;)this.indicators[b].transitionTimingFunction(a)},_translate:function(a,b){this.options.useTransform?this.scrollerStyle[k.style.transform]="translate("+a+"px,"+b+"px)"+this.translateZ:(a=c.round(a),b=c.round(b),this.scrollerStyle.left=a+"px",this.scrollerStyle.top=b+"px");this.x=a;this.y=b;if(this.indicators)for(var d=this.indicators.length;d--;)this.indicators[d].updatePosition()},
_initEvents:function(b){b=b?k.removeEvent:k.addEvent;var c=this.options.bindToWrapper?this.wrapper:a;b(a,"orientationchange",this);b(a,"resize",this);this.options.click&&b(this.wrapper,"click",this,!0);this.options.disableMouse||(b(this.wrapper,"mousedown",this),b(c,"mousemove",this),b(c,"mousecancel",this),b(c,"mouseup",this));k.hasPointer&&!this.options.disablePointer&&(b(this.wrapper,k.prefixPointerEvent("pointerdown"),this),b(c,k.prefixPointerEvent("pointermove"),this),b(c,k.prefixPointerEvent("pointercancel"),
this),b(c,k.prefixPointerEvent("pointerup"),this));k.hasTouch&&!this.options.disableTouch&&(b(this.wrapper,"touchstart",this),b(c,"touchmove",this),b(c,"touchcancel",this),b(c,"touchend",this));b(this.scroller,"transitionend",this);b(this.scroller,"webkitTransitionEnd",this);b(this.scroller,"oTransitionEnd",this);b(this.scroller,"MSTransitionEnd",this)},getComputedPosition:function(){var b=a.getComputedStyle(this.scroller,null),c;this.options.useTransform?(b=b[k.style.transform].split(")")[0].split(", "),
c=+(b[12]||b[4]),b=+(b[13]||b[5])):(c=+b.left.replace(/[^-\d.]/g,""),b=+b.top.replace(/[^-\d.]/g,""));return{x:c,y:b}},_initIndicators:function(){function a(b){for(var c=k.indicators.length;c--;)b.call(k.indicators[c])}var b=this.options.interactiveScrollbars,c="string"!=typeof this.options.scrollbars,d=[],h,k=this;this.indicators=[];this.options.scrollbars&&(this.options.scrollY&&(h={el:g("v",b,this.options.scrollbars),interactive:b,defaultScrollbars:!0,customStyle:c,resize:this.options.resizeScrollbars,
shrink:this.options.shrinkScrollbars,fade:this.options.fadeScrollbars,listenX:!1},this.wrapper.appendChild(h.el),d.push(h)),this.options.scrollX&&(h={el:g("h",b,this.options.scrollbars),interactive:b,defaultScrollbars:!0,customStyle:c,resize:this.options.resizeScrollbars,shrink:this.options.shrinkScrollbars,fade:this.options.fadeScrollbars,listenY:!1},this.wrapper.appendChild(h.el),d.push(h)));this.options.indicators&&(d=d.concat(this.options.indicators));for(b=d.length;b--;)this.indicators.push(new l(this,
d[b]));this.options.fadeScrollbars&&(this.on("scrollEnd",function(){a(function(){this.fade()})}),this.on("scrollCancel",function(){a(function(){this.fade()})}),this.on("scrollStart",function(){a(function(){this.fade(1)})}),this.on("beforeScrollStart",function(){a(function(){this.fade(1,!0)})}));this.on("refresh",function(){a(function(){this.refresh()})});this.on("destroy",function(){a(function(){this.destroy()});delete this.indicators})},_initWheel:function(){k.addEvent(this.wrapper,"wheel",this);
k.addEvent(this.wrapper,"mousewheel",this);k.addEvent(this.wrapper,"DOMMouseScroll",this);this.on("destroy",function(){k.removeEvent(this.wrapper,"wheel",this);k.removeEvent(this.wrapper,"mousewheel",this);k.removeEvent(this.wrapper,"DOMMouseScroll",this)})},_wheel:function(a){if(this.enabled){a.preventDefault();a.stopPropagation();var b,d,g,h=this;void 0===this.wheelTimeout&&h._execEvent("scrollStart");clearTimeout(this.wheelTimeout);this.wheelTimeout=setTimeout(function(){h._execEvent("scrollEnd");
h.wheelTimeout=void 0},400);if("deltaX"in a)1===a.deltaMode?(b=-a.deltaX*this.options.mouseWheelSpeed,a=-a.deltaY*this.options.mouseWheelSpeed):(b=-a.deltaX,a=-a.deltaY);else if("wheelDeltaX"in a)b=a.wheelDeltaX/120*this.options.mouseWheelSpeed,a=a.wheelDeltaY/120*this.options.mouseWheelSpeed;else if("wheelDelta"in a)b=a=a.wheelDelta/120*this.options.mouseWheelSpeed;else if("detail"in a)b=a=-a.detail/3*this.options.mouseWheelSpeed;else return;b*=this.options.invertWheelDirection;a*=this.options.invertWheelDirection;
this.hasVerticalScroll||(b=a,a=0);this.options.snap?(d=this.currentPage.pageX,g=this.currentPage.pageY,0<b?d--:0>b&&d++,0<a?g--:0>a&&g++,this.goToPage(d,g)):(d=this.x+c.round(this.hasHorizontalScroll?b:0),g=this.y+c.round(this.hasVerticalScroll?a:0),0<d?d=0:d<this.maxScrollX&&(d=this.maxScrollX),0<g?g=0:g<this.maxScrollY&&(g=this.maxScrollY),this.scrollTo(d,g,0))}},_initSnap:function(){this.currentPage={};"string"==typeof this.options.snap&&(this.options.snap=this.scroller.querySelectorAll(this.options.snap));
this.on("refresh",function(){var a=0,b,d=0,g,h,k,l=0,p;g=this.options.snapStepX||this.wrapperWidth;var r=this.options.snapStepY||this.wrapperHeight;this.pages=[];if(this.wrapperWidth&&this.wrapperHeight&&this.scrollerWidth&&this.scrollerHeight){if(!0===this.options.snap)for(h=c.round(g/2),k=c.round(r/2);l>-this.scrollerWidth;){this.pages[a]=[];for(p=b=0;p>-this.scrollerHeight;)this.pages[a][b]={x:c.max(l,this.maxScrollX),y:c.max(p,this.maxScrollY),width:g,height:r,cx:l-h,cy:p-k},p-=r,b++;l-=g;a++}else for(r=
this.options.snap,b=r.length,g=-1;a<b;a++){if(0===a||r[a].offsetLeft<=r[a-1].offsetLeft)d=0,g++;this.pages[d]||(this.pages[d]=[]);l=c.max(-r[a].offsetLeft,this.maxScrollX);p=c.max(-r[a].offsetTop,this.maxScrollY);h=l-c.round(r[a].offsetWidth/2);k=p-c.round(r[a].offsetHeight/2);this.pages[d][g]={x:l,y:p,width:r[a].offsetWidth,height:r[a].offsetHeight,cx:h,cy:k};l>this.maxScrollX&&d++}this.goToPage(this.currentPage.pageX||0,this.currentPage.pageY||0,0);0===this.options.snapThreshold%1?this.snapThresholdY=
this.snapThresholdX=this.options.snapThreshold:(this.snapThresholdX=c.round(this.pages[this.currentPage.pageX][this.currentPage.pageY].width*this.options.snapThreshold),this.snapThresholdY=c.round(this.pages[this.currentPage.pageX][this.currentPage.pageY].height*this.options.snapThreshold))}});this.on("flick",function(){var a=this.options.snapSpeed||c.max(c.max(c.min(c.abs(this.x-this.startX),1E3),c.min(c.abs(this.y-this.startY),1E3)),300);this.goToPage(this.currentPage.pageX+this.directionX,this.currentPage.pageY+
this.directionY,a)})},_nearestSnap:function(a,b){if(!this.pages.length)return{x:0,y:0,pageX:0,pageY:0};var d=0,g=this.pages.length,h=0;if(c.abs(a-this.absStartX)<this.snapThresholdX&&c.abs(b-this.absStartY)<this.snapThresholdY)return this.currentPage;0<a?a=0:a<this.maxScrollX&&(a=this.maxScrollX);0<b?b=0:b<this.maxScrollY&&(b=this.maxScrollY);for(;d<g;d++)if(a>=this.pages[d][0].cx){a=this.pages[d][0].x;break}for(g=this.pages[d].length;h<g;h++)if(b>=this.pages[0][h].cy){b=this.pages[0][h].y;break}d==
this.currentPage.pageX&&(d+=this.directionX,0>d?d=0:d>=this.pages.length&&(d=this.pages.length-1),a=this.pages[d][0].x);h==this.currentPage.pageY&&(h+=this.directionY,0>h?h=0:h>=this.pages[0].length&&(h=this.pages[0].length-1),b=this.pages[0][h].y);return{x:a,y:b,pageX:d,pageY:h}},goToPage:function(a,b,d,g){g=g||this.options.bounceEasing;a>=this.pages.length?a=this.pages.length-1:0>a&&(a=0);b>=this.pages[a].length?b=this.pages[a].length-1:0>b&&(b=0);var h=this.pages[a][b].x,l=this.pages[a][b].y;d=
void 0===d?this.options.snapSpeed||c.max(c.max(c.min(c.abs(h-this.x),1E3),c.min(c.abs(l-this.y),1E3)),300):d;this.currentPage={x:h,y:l,pageX:a,pageY:b};this.scrollTo(h,l,d,g)},next:function(a,b){var c=this.currentPage.pageX,d=this.currentPage.pageY;c++;c>=this.pages.length&&this.hasVerticalScroll&&(c=0,d++);this.goToPage(c,d,a,b)},prev:function(a,b){var c=this.currentPage.pageX,d=this.currentPage.pageY;c--;0>c&&this.hasVerticalScroll&&(c=0,d--);this.goToPage(c,d,a,b)},_initKeys:function(b){b={pageUp:33,
pageDown:34,end:35,home:36,left:37,up:38,right:39,down:40};var c;if("object"==typeof this.options.keyBindings)for(c in this.options.keyBindings)"string"==typeof this.options.keyBindings[c]&&(this.options.keyBindings[c]=this.options.keyBindings[c].toUpperCase().charCodeAt(0));else this.options.keyBindings={};for(c in b)this.options.keyBindings[c]=this.options.keyBindings[c]||b[c];k.addEvent(a,"keydown",this);this.on("destroy",function(){k.removeEvent(a,"keydown",this)})},_key:function(a){if(this.enabled){var b=
this.options.snap,d=b?this.currentPage.pageX:this.x,g=b?this.currentPage.pageY:this.y,h=k.getTime(),l=this.keyTime||0,w;this.options.useTransition&&this.isInTransition&&(w=this.getComputedPosition(),this._translate(c.round(w.x),c.round(w.y)),this.isInTransition=!1);this.keyAcceleration=200>h-l?c.min(this.keyAcceleration+.25,50):0;switch(a.keyCode){case this.options.keyBindings.pageUp:this.hasHorizontalScroll&&!this.hasVerticalScroll?d+=b?1:this.wrapperWidth:g+=b?1:this.wrapperHeight;break;case this.options.keyBindings.pageDown:this.hasHorizontalScroll&&
!this.hasVerticalScroll?d-=b?1:this.wrapperWidth:g-=b?1:this.wrapperHeight;break;case this.options.keyBindings.end:d=b?this.pages.length-1:this.maxScrollX;g=b?this.pages[0].length-1:this.maxScrollY;break;case this.options.keyBindings.home:g=d=0;break;case this.options.keyBindings.left:d+=b?-1:5+this.keyAcceleration>>0;break;case this.options.keyBindings.up:g+=b?1:5+this.keyAcceleration>>0;break;case this.options.keyBindings.right:d-=b?-1:5+this.keyAcceleration>>0;break;case this.options.keyBindings.down:g-=
b?1:5+this.keyAcceleration>>0;break;default:return}b?this.goToPage(d,g):(0<d?this.keyAcceleration=d=0:d<this.maxScrollX&&(d=this.maxScrollX,this.keyAcceleration=0),0<g?this.keyAcceleration=g=0:g<this.maxScrollY&&(g=this.maxScrollY,this.keyAcceleration=0),this.scrollTo(d,g,0),this.keyTime=h)}},_animate:function(a,b,c,d){function g(){var z=k.getTime(),A;z>=B?(l.isAnimating=!1,l._translate(a,b),l.resetPosition(l.options.bounceTime)||l._execEvent("scrollEnd")):(z=(z-r)/c,A=d(z),z=(a-w)*A+w,A=(b-p)*A+
p,l._translate(z,A),l.isAnimating&&h(g))}var l=this,w=this.x,p=this.y,r=k.getTime(),B=r+c;this.isAnimating=!0;g()},handleEvent:function(a){switch(a.type){case "touchstart":case "pointerdown":case "MSPointerDown":case "mousedown":this._start(a);break;case "touchmove":case "pointermove":case "MSPointerMove":case "mousemove":this._move(a);break;case "touchend":case "pointerup":case "MSPointerUp":case "mouseup":case "touchcancel":case "pointercancel":case "MSPointerCancel":case "mousecancel":this._end(a);
break;case "orientationchange":case "resize":this._resize();break;case "transitionend":case "webkitTransitionEnd":case "oTransitionEnd":case "MSTransitionEnd":this._transitionEnd(a);break;case "wheel":case "DOMMouseScroll":case "mousewheel":this._wheel(a);break;case "keydown":this._key(a);break;case "click":a._constructed||(a.preventDefault(),a.stopPropagation())}}};l.prototype={handleEvent:function(a){switch(a.type){case "touchstart":case "pointerdown":case "MSPointerDown":case "mousedown":this._start(a);
break;case "touchmove":case "pointermove":case "MSPointerMove":case "mousemove":this._move(a);break;case "touchend":case "pointerup":case "MSPointerUp":case "mouseup":case "touchcancel":case "pointercancel":case "MSPointerCancel":case "mousecancel":this._end(a)}},destroy:function(){this.options.interactive&&(k.removeEvent(this.indicator,"touchstart",this),k.removeEvent(this.indicator,k.prefixPointerEvent("pointerdown"),this),k.removeEvent(this.indicator,"mousedown",this),k.removeEvent(a,"touchmove",
this),k.removeEvent(a,k.prefixPointerEvent("pointermove"),this),k.removeEvent(a,"mousemove",this),k.removeEvent(a,"touchend",this),k.removeEvent(a,k.prefixPointerEvent("pointerup"),this),k.removeEvent(a,"mouseup",this));this.options.defaultScrollbars&&this.wrapper.parentNode.removeChild(this.wrapper)},_start:function(b){var c=b.touches?b.touches[0]:b;b.preventDefault();b.stopPropagation();this.transitionTime();this.initiated=!0;this.moved=!1;this.lastPointX=c.pageX;this.lastPointY=c.pageY;this.startTime=
k.getTime();this.options.disableTouch||k.addEvent(a,"touchmove",this);this.options.disablePointer||k.addEvent(a,k.prefixPointerEvent("pointermove"),this);this.options.disableMouse||k.addEvent(a,"mousemove",this);this.scroller._execEvent("beforeScrollStart")},_move:function(a){var b=a.touches?a.touches[0]:a,c,d;k.getTime();this.moved||this.scroller._execEvent("scrollStart");this.moved=!0;c=b.pageX-this.lastPointX;this.lastPointX=b.pageX;d=b.pageY-this.lastPointY;this.lastPointY=b.pageY;this._pos(this.x+
c,this.y+d);a.preventDefault();a.stopPropagation()},_end:function(b){if(this.initiated){this.initiated=!1;b.preventDefault();b.stopPropagation();k.removeEvent(a,"touchmove",this);k.removeEvent(a,k.prefixPointerEvent("pointermove"),this);k.removeEvent(a,"mousemove",this);if(this.scroller.options.snap){b=this.scroller._nearestSnap(this.scroller.x,this.scroller.y);var d=this.options.snapSpeed||c.max(c.max(c.min(c.abs(this.scroller.x-b.x),1E3),c.min(c.abs(this.scroller.y-b.y),1E3)),300);if(this.scroller.x!=
b.x||this.scroller.y!=b.y)this.scroller.directionX=0,this.scroller.directionY=0,this.scroller.currentPage=b,this.scroller.scrollTo(b.x,b.y,d,this.scroller.options.bounceEasing)}this.moved&&this.scroller._execEvent("scrollEnd")}},transitionTime:function(a){a=a||0;this.indicatorStyle[k.style.transitionDuration]=a+"ms";!a&&k.isBadAndroid&&(this.indicatorStyle[k.style.transitionDuration]="0.001s")},transitionTimingFunction:function(a){this.indicatorStyle[k.style.transitionTimingFunction]=a},refresh:function(){this.transitionTime();
this.indicatorStyle.display=this.options.listenX&&!this.options.listenY?this.scroller.hasHorizontalScroll?"block":"none":this.options.listenY&&!this.options.listenX?this.scroller.hasVerticalScroll?"block":"none":this.scroller.hasHorizontalScroll||this.scroller.hasVerticalScroll?"block":"none";this.scroller.hasHorizontalScroll&&this.scroller.hasVerticalScroll?(k.addClass(this.wrapper,"iScrollBothScrollbars"),k.removeClass(this.wrapper,"iScrollLoneScrollbar"),this.options.defaultScrollbars&&this.options.customStyle&&
(this.options.listenX?this.wrapper.style.right="8px":this.wrapper.style.bottom="8px")):(k.removeClass(this.wrapper,"iScrollBothScrollbars"),k.addClass(this.wrapper,"iScrollLoneScrollbar"),this.options.defaultScrollbars&&this.options.customStyle&&(this.options.listenX?this.wrapper.style.right="2px":this.wrapper.style.bottom="2px"));this.options.listenX&&(this.wrapperWidth=this.wrapper.clientWidth,this.options.resize?(this.indicatorWidth=c.max(c.round(this.wrapperWidth*this.wrapperWidth/(this.scroller.scrollerWidth||
this.wrapperWidth||1)),8),this.indicatorStyle.width=this.indicatorWidth+"px"):this.indicatorWidth=this.indicator.clientWidth,this.maxPosX=this.wrapperWidth-this.indicatorWidth,"clip"==this.options.shrink?(this.minBoundaryX=-this.indicatorWidth+8,this.maxBoundaryX=this.wrapperWidth-8):(this.minBoundaryX=0,this.maxBoundaryX=this.maxPosX),this.sizeRatioX=this.options.speedRatioX||this.scroller.maxScrollX&&this.maxPosX/this.scroller.maxScrollX);this.options.listenY&&(this.wrapperHeight=this.wrapper.clientHeight,
this.options.resize?(this.indicatorHeight=c.max(c.round(this.wrapperHeight*this.wrapperHeight/(this.scroller.scrollerHeight||this.wrapperHeight||1)),8),this.indicatorStyle.height=this.indicatorHeight+"px"):this.indicatorHeight=this.indicator.clientHeight,this.maxPosY=this.wrapperHeight-this.indicatorHeight,"clip"==this.options.shrink?(this.minBoundaryY=-this.indicatorHeight+8,this.maxBoundaryY=this.wrapperHeight-8):(this.minBoundaryY=0,this.maxBoundaryY=this.maxPosY),this.maxPosY=this.wrapperHeight-
this.indicatorHeight,this.sizeRatioY=this.options.speedRatioY||this.scroller.maxScrollY&&this.maxPosY/this.scroller.maxScrollY);this.updatePosition()},updatePosition:function(){var a=this.options.listenX&&c.round(this.sizeRatioX*this.scroller.x)||0,b=this.options.listenY&&c.round(this.sizeRatioY*this.scroller.y)||0;this.options.ignoreBoundaries||(a<this.minBoundaryX?("scale"==this.options.shrink&&(this.width=c.max(this.indicatorWidth+a,8),this.indicatorStyle.width=this.width+"px"),a=this.minBoundaryX):
a>this.maxBoundaryX?"scale"==this.options.shrink?(this.width=c.max(this.indicatorWidth-(a-this.maxPosX),8),this.indicatorStyle.width=this.width+"px",a=this.maxPosX+this.indicatorWidth-this.width):a=this.maxBoundaryX:"scale"==this.options.shrink&&this.width!=this.indicatorWidth&&(this.width=this.indicatorWidth,this.indicatorStyle.width=this.width+"px"),b<this.minBoundaryY?("scale"==this.options.shrink&&(this.height=c.max(this.indicatorHeight+3*b,8),this.indicatorStyle.height=this.height+"px"),b=this.minBoundaryY):
b>this.maxBoundaryY?"scale"==this.options.shrink?(this.height=c.max(this.indicatorHeight-3*(b-this.maxPosY),8),this.indicatorStyle.height=this.height+"px",b=this.maxPosY+this.indicatorHeight-this.height):b=this.maxBoundaryY:"scale"==this.options.shrink&&this.height!=this.indicatorHeight&&(this.height=this.indicatorHeight,this.indicatorStyle.height=this.height+"px"));this.x=a;this.y=b;this.scroller.options.useTransform?this.indicatorStyle[k.style.transform]="translate("+a+"px,"+b+"px)"+this.scroller.translateZ:
(this.indicatorStyle.left=a+"px",this.indicatorStyle.top=b+"px")},_pos:function(a,b){0>a?a=0:a>this.maxPosX&&(a=this.maxPosX);0>b?b=0:b>this.maxPosY&&(b=this.maxPosY);a=this.options.listenX?c.round(a/this.sizeRatioX):this.scroller.x;b=this.options.listenY?c.round(b/this.sizeRatioY):this.scroller.y;this.scroller.scrollTo(a,b)},fade:function(a,b){if(!b||this.visible){clearTimeout(this.fadeTimeout);this.fadeTimeout=null;var c=a?0:300;this.wrapperStyle[k.style.transitionDuration]=(a?250:500)+"ms";this.fadeTimeout=
setTimeout(function(a){this.wrapperStyle.opacity=a;this.visible=+a}.bind(this,a?"1":"0"),c)}}};d.utils=k;"undefined"!=typeof module&&module.exports?module.exports=d:a.IScroll=d})(window,document,Math);var ie=document.all,ns6=document.getElementById&&!document.all,isGecko="Gecko"==navigator.product,allowedPopups=1,isMenu=!1,activepopup=null,psubdiv=null,myScroll=null,onCallback=null,offCallback=null;function menuMouseSelect(){return 0>=allowedPopups?(removePopup(),null!=myScroll&&myScroll.destroy(),myScroll=null,!1):!0}function popupActive(){return null!=activepopup}function onPopup(a,b){onCallback=a;offCallback=b}
function createItem(a,b,c){function d(a,b,c){a.active||(a.className+=" ITEM_selected",a.active=!0,setTimeout(function(){removePopup();b(c);a.active=!1},300))}var g=document.createElement("div");g.origCls="";isMobile&&g.addEventListener("tap",function(){d(g,b,c);e.cancelBubble=!0},!1);g.onmouseup=function(a){d(g,b,c);a.cancelBubble=!0};g.onmousedown=function(a){d(g,b,c);a.cancelBubble=!0};g.onmouseover=function(a){g.origCls=g.className;g.className+=" ITEM_hover"};g.onmouseout=function(a){g.className=
g.origCls};g.appendChild(document.createTextNode(a));return g}function PopupMenu(a,b){this.heading=this.menudiv=this.lastItem=null}PopupMenu.prototype.clear=function(){this.lastItem=null;this.menudiv=document.createElement("div")};PopupMenu.prototype.setHeading=function(a){this.heading=a};PopupMenu.prototype.add=function(a,b,c){null==a?this.lastItem.className="ITEM_sep":(this.lastItem=createItem(null==a?"":a,null==b?"":b,c),this.menudiv.appendChild(this.lastItem))};
PopupMenu.prototype.activate=function(a,b,c){this.lastItem.className="ITEM_last";isMenu=!0;wrapper=document.createElement("div");if(null!=this.heading){var d=document.createElement("H1"),g=document.createTextNode(this.heading);d.appendChild(g);wrapper.appendChild(d)}wrapper.appendChild(this.menudiv);wrapper.style.display="none";wrapper.className="POPUPMENU";popup(a,wrapper,b,c,!1);return wrapper};
function removePopup(){null!=activepopup&&(null!=offCallback&&offCallback(),isMenu=!1,allowedPopups++,activepopup.style.display="none",activepopup.parentNode.removeChild(activepopup),activepopup=null)}
function popupwindow(a,b,c,d,g,l,h){var k=document.createElement("div");k.className="POPUP";k.innerHTML=b;null!=l&&(k.id=l);h?setTimeout(function(){popup(a,k,c,d,g)},900):popup(a,k,c,d,g);k.onmousedown=function(a){a=a?a:event?event:null;a.cancelBubble=!0;return null};k.onmouseup=function(a){a=a?a:event?event:null;a.cancelBubble=!0;return null};k.onclick=function(a){a=a?a:event?event:null;a.cancelBubble=!0;return null};k.onmousemove=function(a){a=a?a:event?event:null;a.cancelBubble=!0;return null};
return k}function remotepopupwindow(a,b,c,d,g){var l=popupwindow(a,"",c,d,!1,g,!1);call(b,null,function(a){l.innerHTML=a});return l}function remotepopupwindowCSS(a,b,c,d,g){call(b,null,function(b){b=popupwindow(a,b,1,1,!1,null,!1);null!=g&&(b.className=g)})}
function popupImage(a,b,c){0>=allowedPopups||(image=document.createElement("img"),activepopup=document.createElement("div"),a.appendChild(activepopup),activepopup.appendChild(image),image.src="images/cross.gif",image.style.position="absolute",image.style.left=b-11+"px",image.style.top=c-11+"px",image.style.zIndex=1001,allowedPopups--,null!=onCallback&&onCallback())}
function popup(a,b,c,d,g){function l(){k=c+4+b.clientWidth-document.body.clientWidth;0<k&&(n=!0,c-=k,1>c&&(c=1),null!=h&&(h.style.left=k-9+"px"));m=d+4+b.clientHeight-document.body.clientHeight;0<m&&(yoffs=!0,d-=m,1>d&&(d=1),null!=h&&(h.style.top=m-12+"px"));if(u||0<k||0<m)activepopup.style.left=c-3+"px",activepopup.style.top=d-3+"px";u=!1;n&&yoffs&&null!=h&&(h.style.display="none")}if(!(0>=allowedPopups)){var h;psubdiv=activepopup=b;null!=g&&g&&(h=document.createElement("img"),activepopup.appendChild(h),
h.src="images/cross.gif",h.style.position="absolute",h.style.left="-9px",h.style.top="-12px",h.style.zIndex=1001,activepopup=document.createElement("div"),activepopup.appendChild(psubdiv),activepopup.onclick=function(a){psubdiv.style.display="none"});a.appendChild(activepopup);var k=0,m=0,n=yoffs=!1,u=!0;activepopup.style.position="absolute";activepopup.style.display="block";activepopup.style.padding="2px";activepopup.style.cursor="default";500>document.body.clientWidth&&b.clientWidth>document.body.clientWidth&&
(activepopup.style.minWidth=document.body.clientWidth+"px");b.clientHeight+10>document.body.clientHeight?(activepopup.style.maxHeight=document.body.clientHeight-5+"px",b.id="wrapper",isMobile?setTimeout(function(){myScroll=new IScroll(activepopup,{scrollbars:!0,tap:!0})},1E3):activepopup.style.overflowY="scroll"):activepopup.style.overflowY="visible";l();setTimeout(l,500);activepopup.style.zIndex=1301;ie||(g=document.createEvent("MouseEvents"),g.initMouseEvent("mouseup",!0,!0,window,c,d,c,d,220,!1,
!1,!0,!1,0,null),a.dispatchEvent(g));allowedPopups--;null!=onCallback&&onCallback()}}function fullPopupWindow(a,b,c,d){eval("this."+a+"=window.open('"+b+"','"+a+"','"+("left=50,top=100,width="+c+",height="+d+"resizable=1,scrollbars=1")+"');");window.focus&&setTimeout(function(){eval("if(this."+a+") this."+a+".focus();")},2E3)};(function(a){if("function"===typeof define&&define.amd)define(a);else if("object"===typeof exports)module.exports=a();else{var b=window.Cookies,c=window.Cookies=a();c.noConflict=function(){window.Cookies=b;return c}}})(function(){function a(){for(var a=0,b={};a<arguments.length;a++){var g=arguments[a],l;for(l in g)b[l]=g[l]}return b}function b(c){function d(b,l,h){var k;if(1<arguments.length){h=a({path:"/"},d.defaults,h);if("number"===typeof h.expires){var m=new Date;m.setMilliseconds(m.getMilliseconds()+
864E5*h.expires);h.expires=m}try{k=JSON.stringify(l),/^[\{\[]/.test(k)&&(l=k)}catch(v){}l=c.write?c.write(l,b):encodeURIComponent(String(l)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,decodeURIComponent);b=encodeURIComponent(String(b));b=b.replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent);b=b.replace(/[\(\)]/g,escape);return document.cookie=[b,"=",l,h.expires&&"; expires="+h.expires.toUTCString(),h.path&&"; path="+h.path,h.domain&&"; domain="+h.domain,h.secure?"; secure":
""].join("")}b||(k={});for(var m=document.cookie?document.cookie.split("; "):[],n=/(%[0-9A-Z]{2})+/g,u=0;u<m.length;u++){var q=m[u].split("="),t=q[0].replace(n,decodeURIComponent),q=q.slice(1).join("=");'"'===q.charAt(0)&&(q=q.slice(1,-1));try{q=c.read?c.read(q,t):c(q,t)||q.replace(n,decodeURIComponent);if(this.json)try{q=JSON.parse(q)}catch(v){}if(b===t){k=q;break}b||(k[t]=q)}catch(v){}}return k}d.get=d.set=d;d.getJSON=function(){return d.apply({json:!0},[].slice.call(arguments))};d.defaults={};
d.remove=function(b,c){d(b,"",a(c,{expires:-1}))};d.withConverter=b;return d}return b(function(){})});function dateFromISO8601(a){a=a.match(/\d+/g);return new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5])}function WXreport(a){this.url=a}
WXreport.prototype.doTextReport=function(a,b){(function(a,b){return call(a,this,function(a){var c;if(10>a.length)c=!1;else{c=[];a=(new DOMParser).parseFromString(a,"text/xml").getElementsByTagName("time");for(var h=0;h<a.length;h++){c[h]=[];c[h].from=dateFromISO8601(a[h].getAttribute("from"));c[h].to=dateFromISO8601(a[h].getAttribute("to"));var k=a[h].getElementsByTagName("location");c[h].name=k[0].getAttribute("name");k=k[0].getElementsByTagName("forecast");c[h].fcast=k[0].textContent}}b&&b(c)},
!1,!0)})(this.url+"/textlocation/1.0/?language=nb;latitude="+a.lat+";longitude="+a.lng+";",b)};function statkartWPS(a){this.url=a}
statkartWPS.prototype.doElevation=function(a,b){function c(a){if(!a)return null;var b=a.getAttribute("dataType");a=a.textContent;if("string"==b)return a;if("integer"==b)return parseInt(a,10);if("float"==b)return parseFloat(a)}(function(a,b){return call(a,this,function(a){var d;if(10>a.length)d=!1;else{d=[];a=(new DOMParser).parseFromString(a,"text/xml").documentElement.getElementsByTagNameNS("*","Output");for(var k=0;k<a.length;k++){var m=a[k].getElementsByTagNameNS("*","Identifier"),n=a[k].getElementsByTagNameNS("*",
"LiteralData");m&&m[0]&&n&&(d[m[0].textContent]=c(n[0]))}}b&&b(d)},!1,!0)})(this.url+"?request=Execute&service=WPS&version=1.0.0&identifier=elevation&datainputs=[lat="+a.lat+";lon="+a.lng+";]",b)};function statkartName(a){this.url=a}
statkartName.prototype.doSearch=function(a,b){function c(a,b){return a.getElementsByTagName(b)[0].childNodes[0].nodeValue}(function(a,b){return call(a,this,function(a){var d;if(10>a.length)d=!1;else{d=[];a=(new DOMParser).parseFromString(a,"text/xml").documentElement.childNodes;for(var k=0,m=0;m<a.length;m++)"stedsnavn"==a[m].nodeName&&(d[k]=[],d[k].type=c(a[m],"navnetype"),d[k].kommune=c(a[m],"kommunenavn"),d[k].fylke=c(a[m],"fylkesnavn"),d[k].navn=c(a[m],"stedsnavn"),d[k].east=c(a[m],"aust"),d[k].north=
c(a[m],"nord"),k++)}if(b){a="<table>";for(k=0;k<d.length;k++)m=(new UTMRef(parseInt(d[k].east),parseInt(d[k].north),"W",33)).toLatLng(),a+='<tr onclick="gotoPos('+m.lng+","+m.lat+')"><td>'+d[k].navn+"</td><td>"+d[k].type+"</td><td>"+d[k].fylke+"</td></tr>";b(a+"</table>")}},!1,!0)})(this.url+"?navn="+a,b)};var sar_key=null,_tryAuth=!1;function setTryAuth(){_tryAuth=!0}function tryAuth(){return(_tryAuth="true"==Cookies.get("polaric.tryLogin"))||getLogin()}function failAuth(){_tryAuth=!1;Cookies.get("polaric.tryLogin")}function failedAuth(){return!_tryAuth}function isLoggedIn(){return null!=myOverlay.meta.loginuser&&"true"==myOverlay.meta.loginuser}function canUpdate(){return isLoggedIn()&&null!=myOverlay.meta.updateuser&&"true"==myOverlay.meta.updateuser}
function isAdmin(){return isLoggedIn()&&null!=myOverlay.meta.adminuser&&"true"==myOverlay.meta.adminuser}function getLogin(){return null!=sar_key||window.location.href.match(/.*\/sar_[0-9a-f]+/)?"-SAR-":/null/.test(myOverlay.meta.login)?null:myOverlay.meta.login}function show_SAR_access(a){var b=document.getElementById("sarmode");null!=b&&(b.innerHTML=a?'<img src="images/sar-o.png">':'<img src="images/sar.png">')}
function setSarKey(a){sar_key=a;storage.removeItem("polaric.sarkey");storage["polaric.sarkey"]=a}function removeSarKey(){sar_key=null;storage.removeItem("polaric.sarkey")}function logout(){jQuery.ajax({type:"GET",url:"/login.php",async:!1,username:"logmeout",password:"---",headers:{Authorization:"Basic xxx"}}).done(function(){}).fail(function(){window.location=""});return!1};var client=0;
window.onmessage=function(a){function b(a){return"T"==a||"t"==a||"true"==a}a=a?a:d?d:null;var c=a.data.split("##"),d=c[0].split("#");"labelUp"==d[0]?labelStyle.next():"labelDown"==d[0]&&labelStyle.previous();if("zoomIn"==d[0])myKaMap.zoomIn();else if("zoomOut"==d[0])myKaMap.zoomOut();else if("zoomScale"==d[0])d=parseInt(c[1],10),isNaN(d)||myKaMap.zoomToScale(d);else if("gotoPos"==d[0])gotoPos(c[1],c[2]);else if("gotoUtm"==d[0]){var d=c[1].substring(0,2),g=c[1].substring(2,3);doRefSearchUtm(c[2],c[3],
g,d,!0)}else if("findItem"==d[0])findItem(c[1],b(c[2]));else if("searchItems"==d[0])searchItems(c[1],""==c[2]?null:c[2],function(b){a.source.postMessage(c[0]+"##"+b,a.origin)});else if("searchNames"==d[0])skNames.doSearch(c[1],function(b){a.source.postMessage(c[0]+"##"+b,a.origin)});else if("xmlPoints"==d[0])getXmlPoints(function(b){a.source.postMessage(c[0]+"##"+b,a.origin)});else if("selectMap"==d[0])myKaMap.selectMap(c[1]);else if("selectBaseLayer"==d[0])myKaMap.selectBaseLayer(c[1]);else if("selectProfile"==
d[0])filterProfiles.selectProfile(c[1]);else if("_subscribe"==d[0]){var d=c[1];if("XMLOVERLAY_LOAD"==d){var l=client=(client+1)%1E5,h=a.origin,k=a.source;myOverlay.registerForEvent(XMLOVERLAY_LOAD,null,function(){k.postMessage("EVENT#"+l,h)});a.source.postMessage(c[0]+"##"+l,a.origin)}"MAP_EXTENTS_CHANGED"==d&&(l=client=(client+1)%1E5,h=a.origin,k=a.source,myKaMap.registerForEvent(KAMAP_EXTENTS_CHANGED,null,function(){k.postMessage("EVENT#"+l,h)}),a.source.postMessage(c[0]+"##"+l,a.origin))}};
function getXmlPoints(a){for(var b="<table>",c=0;c<myOverlay.ovrObjects.length;c++){var d=myOverlay.ovrObjects[c];null!=d&&(b+="<tr><td onclick=\"findItem('"+d.pid+"',true);\">"+("__sign"!=d.pid.substring(0,6)?d.pid:"")+"</td><td>"+d.title+"</td></tr>")}a(b+"</table>")}
function findItem(a,b){call(server_url+"srv/finditem?ajax=true&lang="+language+"&id="+a,null,function(a){if(null!=a){var d=a.split(/\s*,\s*/g);if(!(null==d||3>d.length)){var g=parseFloat(d[1]),l=parseFloat(d[2]);isNaN(g)||isNaN(l)||(myKaMap.zoomTo(g,l),b&&setTimeout(function(){popup_stationInfoGeo(d[0],!1,g,l)},1400),setTimeout(function(){var a=myOverlay.getPointObject(d[0]);null!=a&&a.moveToFront();null!=a&&a.flash()},1100))}}},!1);b||(b=!1)}
function gotoPos(a,b,c){removePopup();doRefSearch(new LatLng(parseFloat(b),parseFloat(a)),c)}function doRefSearchLocal(a,b){removePopup();var c=parseInt(a,10),d=parseInt(b,10);if(!isNaN(c)&&!isNaN(d)){var g=myKaMap.getCenter(),g=(new LatLng(g.lat,g.lon)).toUTMRef(),c=new UTMRef(1E5*Math.floor(g.easting/1E5)+100*c,1E5*Math.floor(g.northing/1E5)+100*d,g.latZone,g.lngZone);doRefSearch(c.toLatLng())}}
function doRefSearchDM(a,b,c,d){removePopup();a=parseInt(a,10);b=parseFloat(b);c=parseInt(c,10);d=parseFloat(d);d=new LatLng(a+b/60,c+d/60);doRefSearch(d)}function doRefSearchUtm(a,b,c,d,g){removePopup();a=parseInt(a,10);b=parseInt(b,10);d=parseInt(d,10);isNaN(a)||isNaN(b)||isNaN(d)||(c=(new UTMRef(a,b,c,d)).toLatLng(),doRefSearch(c,g))}function doRefSearch(a,b){myKaMap.zoomTo(a.lng,a.lat);setTimeout(function(){popup_posInfo(a,b)},1500)}
function searchItems(a,b,c){var d=sarUrl()+(getLogin()?"srv/search_sec?":"srv/search?");call(d+"ajax=true&lang="+language+(null!=a&&""!=a?"&srch="+a:"")+(null!=b&&""!=a?"&tags="+b:"")+(1==isMobile?"&mobile=true":""),null,c,!1)}function getTags(a,b,c){call(server_url+"srv/tags?ajax=true&lang="+language+(null!=a?"&item="+a:"")+(null!=b?"&tags="+b:"")+(1==isMobile?"&mobile=true":""),null,c,!1)};function ContextMenu(){this.callbacks=[];this.txt=new PopupMenu(null)}ContextMenu.prototype.addCallback=function(a,b){this.callbacks[a]||(this.callbacks[a]=[]);this.callbacks[a].push(b)};
ContextMenu.prototype.show=function(a,b,c,d){var g=ident=a;b=b?b:event?event:null;c=c?c:b.pageX?b.pageX:b.clientX;d=d?d:b.pageY?b.pageY:b.clientY;var l=myKaMap.domObj;a=myOverlay.getPointObject(ident);this.txt.clear();this.txt.ident=ident;this.txt.x=c;this.txt.y=d;this.txt.p=a;null==ident?g="MAP":null!=a&&(g=a.isSign?"SIGN":"ITEM");var h=this.callbacks[g];if(h)for(a=0;a<h.length;a++)f=h[a],null!=f&&f(this.txt);b.cancelBubble=!0;menuMouseSelect();this.txt.activate(l,c,d).className+=" ctxt_"+g};
function showContextMenu(a,b,c){b=b?b:event?event:null;x=a.offsetLeft+10;y=a.offsetTop+a.offsetHeight-2;ctxtMenu.show(c,b,x,y);b.cancelBubble=!0;return!1}function addContextMenu(a,b){var c=document.getElementById(a);c.onclick=function(a){return showContextMenu(c,a,b)};c.oncontextmenu=function(a){return showContextMenu(c,a,b)}};var _mapupdate_suspend=!1,_mapupdate_retry=0;
function mapupdate_init(){var a=window.location,b;b="https:"===a.protocol?"wss":"ws";b+="://"+a.host+a.pathname;b+=tryAuth()?"ws/mapdata_sec":"ws/mapdata";websocket=new WebSocket(b);websocket.onopen=function(){OpenLayers.Console.info("Connected to server (for XML overlay).");setTimeout(function(){mapupdate_subscribe()},1E3)};websocket.onmessage=function(a){_mapupdate_suspend||myOverlay.applyXml(a.data)};websocket.onclose=function(a){_mapupdate_retry++;3>=_mapupdate_retry?setTimeout(function(){OpenLayers.Console.info("Attempt reconnect to server (for XML overlay).");
mapupdate_init()},15E3):(_mapupdate_retry=0,OpenLayers.Console.error("Lost connection to server (for XML overlay)."),alert(_("ERROR: Lost connection to server")))};websocket.onerror=function(a){failedAuth()?(OpenLayers.Console.error("Failed to connect to server (for XML overlay)."),alert(_("ERROR: Failed to connect to server"))):(failAuth(),mapupdate_init())}}function mapupdate_suspend(a){_mapupdate_suspend=!0;setTimeout(function(){_mapupdate_suspend=!1},a)}
function mapupdate_close(){websocket.close()}function mapupdate_subscribe(){_mapupdate_suspend=!1;var a=myKaMap.getGeoExtents(),b="";null!=filterProfiles.selectedProf()&&(b=filterProfiles.selectedProf());websocket.send("SUBSCRIBE,"+b+","+roundDeg(a[0])+","+roundDeg(a[1])+","+roundDeg(a[2])+","+roundDeg(a[3])+","+currentScale)};function MessageBuffer(a){this.messages=[];this.msgs_current=this.msgs_cnt=this.msgs_index=0;this.MAX=a}MessageBuffer.prototype.putMessage=function(a){this.msgs_cnt==this.MAX?this.msgs_index=(this.msgs_index+1)%this.MAX:this.msgs_cnt++;var b=(this.msgs_index+this.msgs_cnt)%this.MAX;this.messages[b]=a;this.msgs_current=b};MessageBuffer.prototype.getMessage=function(a){return this.messages[a]};MessageBuffer.prototype.lastIndex=function(){return this.msgs_index+this.msgs_cnt};
MessageBuffer.prototype.currIndex=function(){return this.msgs_current};MessageBuffer.prototype.hasOlder=function(){return 1<this.msgs_cnt&&this.msgs_current!=(this.msgs_index+1)%this.MAX};MessageBuffer.prototype.hasNewer=function(){return 1<this.msgs_cnt&&this.msgs_current!=(this.msgs_index+this.msgs_cnt)%this.MAX};MessageBuffer.prototype.incrementIndex=function(){this.hasNewer()&&(this.msgs_current=(this.msgs_current+1)%this.MAX);return this.msgs_current};
MessageBuffer.prototype.decrementIndex=function(){this.hasOlder()&&(this.msgs_current--,0>this.msgs_current&&(this.msgs_current+=this.MAX));return this.msgs_current};var msgbuf=new MessageBuffer(10);
function message_init(){if(tryAuth()){var a=window.location,b;b="https:"===a.protocol?"wss":"ws";b+="://"+a.host+a.pathname;websocket=new WebSocket(b+"ws/messages_sec");websocket.onopen=function(){OpenLayers.Console.info("Connected to server (for messaging).")};websocket.onmessage=function(a){a=JSON.parse(a.data);msgbuf.putMessage(a);popup_showMessage(msgbuf.currIndex())};websocket.onclose=function(a){};websocket.onerror=function(a){OpenLayers.Console.info("Failed to connect to server (for messaging).")}}}
function message_close(){websocket.close()}function message_send(a){websocket.send(JSON.stringify(a))}Date.prototype.toLocaleFormat=Date.prototype.toLocaleFormat||function(a){return a.replace(/%Y/g,this.getFullYear()).replace(/%m/g,this.getMonth()+1).replace(/%d/g,this.getDate()).replace(/%H/g,this.getHours()).replace(/%M/g,this.getMinutes())};
function popup_showMessage(a){removePopup();a=msgbuf.getMessage(a);popupwindow(document.getElementById("anchor"),"<div><h1>"+_("Incoming message")+'</h1><div id="messageform"><form> <span class="sleftlab">From:</span>'+a.from+'<br/><span class="sleftlab">To:</span>'+a.to+'<br/><span class="sleftlab">Time:</span>'+(new Date(a.time)).toLocaleFormat("%H:%M")+'<br/><div id="msgtext">'+a.text+"</div>"+function(){var a=msgbuf.hasOlder()?'<button id="obutton"><img src="images/back.png"></img></button>':
"",c=msgbuf.hasNewer()?'<button id="nbutton"><img src="images/fwd.png"></img></button>':"";return a+c}()+"</form></div></div>",50,70,null);$("#obutton").click(function(a){a=a?a:event?event:null;a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation();popup_showMessage(msgbuf.decrementIndex())});$("#nbutton").click(function(a){a=a?a:event?event:null;a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation();popup_showMessage(msgbuf.incrementIndex())})}
function popup_sendMessage(){fullPopupWindow("Message",server_url+"srv/sendmsg?lang="+language,390,220)};var toolbar=document.getElementById("toolbar"),gpsTracker=null,ctxtMenu=new ContextMenu;
ctxtMenu.addCallback("MAP",function(a){a.add(_("Show map reference"),function(){setTimeout("popup_posInfoPix("+a.x+", "+a.y+");",100)});WXreport_enable&&a.add(_("WX report (Norway)"),function(){setTimeout("popup_wxInfoPix("+a.x+", "+a.y+");",100)});a.add(_("Add Rescue mission"),function(){popup_addRescueMission(a.x,a.y)});canUpdate()&&a.add(_("Add APRS object"),function(){popup_editObject(a.x,a.y)});isAdmin()&&a.add(_("Set own position"),function(){popup_setOwnPos(a.x,a.y)});a.add(null);a.add(_("Center point"),
function(){myKaMap.zoomToPix(a.x,a.y)});a.add(_("Zoom in"),function(){myKaMap.zoomIn()});a.add(_("Zoom out"),function(){myKaMap.zoomOut()})});
ctxtMenu.addCallback("MAIN",function(a){a.d=toolbar;a.add(_("Search station/object"),function(){setTimeout("popup_searchItems();",100)});a.add(_("Find map reference"),function(){setTimeout("popup_refSearch();",100)});a.add(_("Add rescue mission"),function(){popup_addRescueMission(null,null)});statkartName_enable&&a.add(_("Find location name (Norway)"),function(){setTimeout("popup_searchNames();",100)});canUpdate()&&(a.add(_("Add object"),function(){popup_editObject(null,null)}),a.add(_("Remove object"),
function(){popup_deleteObject(null)}));canUpdate()&&a.add(_("Send instant message"),function(){setTimeout("popup_sendMessage();",100)});a.add(null);isMobileApp&&(a.add(_("Set SAR code"),popup_setSarKey),null!=gpsTracker&&gpsTracker.isActive()?a.add(_("De-activate GPS pos."),function(){gpsTracker.deactivate()}):a.add(_("Activate GPS pos."),function(){null==gpsTracker&&(gpsTracker=new GpsTracker);gpsTracker.activate()}),a.add(_("Change language"),function(){popup_setLanguage()}));traceIsHidden("ALL")?
a.add(_("Show traces"),function(){myOverlay.showPointTrace("ALL")}):a.add(_("Hide traces"),function(){myOverlay.hidePointTrace("ALL")});a.add(null);a.add(_("Font size +"),function(){labelStyle.next()});a.add(_("Font size -"),function(){labelStyle.previous()});isAdmin()||canUpdate()?(a.add(null),sarUrl&&a.add(_("SAR URL"),popup_sarUrl),a.add(_("SAR mode"),popup_sarMode),a.add(null),a.add(_("Log out"),logout)):(a.add(null),a.add(_("Log in"),function(){window.location="login.php"}))});
ctxtMenu.addCallback("SIGN",function(a){a.add(_("Show info"),function(){setTimeout(function(){popup_signInfo(a.p,a.x,a.y)})})});
ctxtMenu.addCallback("ITEM",function(a){a.add(_("Show info"),function(){popup_stationInfo(a.ident,!1,a.x,a.y)});a.p.flags.match("t")&&a.add(_("Telemetry"),function(){popup_telemetry(a.ident,a.x,a.y)});null!=a.p&&a.p.hasTrace&&a.add(_("Last movements"),function(){popup_stationHistory(a.ident,a.x,a.y)});canUpdate()&&(a.add(_("Global settings.."),function(){popup_stationInfo(a.ident,!0)}),a.add(_("Manage tags.."),function(){popup_setTag(a.ident,a.x,a.y)}),null!=a.p&&(a.p.own?a.add(_("Remove object"),
function(){popup_deleteObject(a.ident)}):a.add(_("Reset info"),function(){popup_resetInfo(a.ident)})));a.add(null);a.add(_("Auto-tracking")+" "+(isTracked(a.ident)?_("OFF"):_("ON")),function(){toggleTracked(a.ident)});labelIsHidden(a.ident)?a.add(_("Show ident"),function(){showPointLabel(a.ident)}):a.add(_("Hide ident"),function(){hidePointLabel(a.ident)});hasTrace(ident)&&(traceIsHidden(a.ident)?a.add(_("Show trail"),function(){myOverlay.showPointTrace(a.ident)}):a.add(_("Hide trail"),function(){myOverlay.hidePointTrace(a.ident)}))});
function popup_setTag(a,b,c){c=myKaMap.pixToGeo(b,c);fullPopupWindow("editTags",server_url+"srv/addtag?objid="+a+"&lang="+language+(null==b?"":"&x="+c[0]+"&y="+c[1]),560,300)}function popup_editObject(a,b){var c=myKaMap.pixToGeo(a,b);fullPopupWindow("editObject",server_url+"srv/addobject?lang="+language+(null==a?"":"&x="+c[0]+"&y="+c[1]),560,300)}
function popup_addRescueMission(a,b){var c=myKaMap.pixToGeo(a,b);fullPopupWindow("addRescueMission",server_url+"srv/addmission?lang="+language+(null==a?"":"&x="+c[0]+"&y="+c[1]),560,300)}function popup_setOwnPos(a,b){var c=myKaMap.pixToGeo(a,b);fullPopupWindow("Position",server_url+"srv/setownpos?lang="+language+(null==a?"":"&x="+c[0]+"&y="+c[1]),500,200)}function popup_deleteObject(a){fullPopupWindow("delObject",server_url+"srv/deleteobject?lang="+language+(null==a?"":"&objid="+a),350,180)}
function popup_resetInfo(a){fullPopupWindow("Station",server_url+"srv/resetinfo?lang="+language+(null==a?"":"&objid="+a),360,180)}function popup_sarMode(){fullPopupWindow("SarMode",server_url+"srv/sarmode?lang="+language,500,320)}
function popup_signInfo(a,b,c){var d=new LatLng(a.geoy,a.geox),g=""+d.toUTMRef();showUTMstring(g);popupwindow(myKaMap.domObj,' <span class="sleftlab">'+_("Description")+":</span>"+a.title+' <br/><span class="sleftlab">UTM:</span>'+showUTMstring(g)+' <br/><nobr><span class="sleftlab">Latlong:</span>'+showDMstring(d.lat)+"N, "+showDMstring(d.lng)+"E <div></div>",b,c,null)}
function popup_stationInfo(a,b,c,d){b?(c=server_url+(getLogin()?"srv/station_sec?id=":"srv/station?id="),fullPopupWindow(_("Station"),c+a+(b?"&edit=true":"")+"&lang="+language,780,600)):remotepopupwindow(myKaMap.domObj,server_url+"srv/station?lang="+language+"&ajax=true&simple=true&id="+a+(b?"&edit=true":""),c,d,"infopopup")}function popup_stationInfoGeo(a,b,c,d){b=myKaMap.geoToPix(c,d);popup_stationInfo(a,!1,b[0]+12,b[1]+10)}
function popup_telemetry(a,b,c){function d(a){if(null!=a){var b=document.getElementById("tlmhist");null!=b&&(b.innerHTML=a,$("#listbutton").hide(),removePopup(),setTimeout(function(){popup(myKaMap.domObj,g,b,c,null)},500))}}var g=remotepopupwindow(myKaMap.domObj,server_url+"srv/telemetry?lang="+language+"&id="+a,b,c,"infopopup");setTimeout(function(){$("#listbutton").click(function(b){call(server_url+"srv/telhist?lang="+language+"&id="+a,null,d,!1)})},2E3)}
function popup_sarUrl(a,b){var c=document.getElementById("permolink").children[0].children[0].href;remotepopupwindow(myKaMap.domObj,server_url+"srv/sarurl?url="+escape(c)+"&lang="+language,50,80)}function popup_stationHistory(a,b,c){remotepopupwindow(myKaMap.domObj,server_url+"srv/history?ajax=true&lang="+language+"&simple=true&id="+a,b,c)}
function popup_setSarKey(){popupwindow(document.getElementById("anchor")," <div><h1>"+_("Set SAR code")+'</h1><div id="sarcodeform"><form>  '+_("Code")+': <input type="text" style="width: 6em" width="6" id="sarcode" value="'+(null==sar_key?"":sar_key)+'"/>&nbsp;  <input id="sarcodebutton" type="button" value="'+_("Confirm")+'" /></div><br></div>',50,70,null);$("#sarcodebutton").click(function(a){var b=$("#sarcode").val();if(""==b||" "==b)b=null;setSarKey(b);removePopup();a.cancelBubble=!0;a.stopPropagation&&
a.stopPropagation()})}
function popup_searchItems(){function a(){var a="";$("div.taglist>input").each(function(b){1==$(this).prop("checked")&&(a=a+(""==a?"":",")+$(this).prop("id").substring(4))});return a}function b(c){null!=c&&($("#tags").html(c),$("div.taglist>input").change(function(c){getTags(null,a(),b)}))}function c(a){if(null!=a){var b=isMobile?document.getElementById("searchform"):document.getElementById("searchresult");null!=b&&(b.innerHTML=a,removePopup(),setTimeout(function(){popup(document.getElementById("anchor"),d,
50,70,null)},500))}}var d=popupwindow(document.getElementById("anchor")," <div><h1>"+_("Search station/object")+'</h1><div id="searchform"><form> '+_("Keywords (tags)")+': <br><div id="tags"></div> '+_("Free text search")+': <input type="text"  width="10" id="search" value="*"/>  <input id="searchbutton" type="button" value="'+_("Search")+'" /> </form><br><div id="searchresult"></div></div></div>',50,70,null);getTags(null,null,b);$("#searchbutton").click(function(b){b=b?b:event?event:null;b.cancelBubble=
!0;b.stopPropagation&&b.stopPropagation();searchItems($("#search").val(),a(),c)})}var downStrokeField;function autojump(a,b){var c=document.getElementById(a);c.nextField=document.getElementById(b);c.onkeydown=autojump_keyDown;c.onkeyup=autojump_keyUp}function autojump_keyDown(){this.beforeLength=this.value.length;downStrokeField=this}
function autojump_keyUp(){this==downStrokeField&&this.value.length>this.beforeLength&&this.value.length>=this.maxLength&&this.nextField.focus();downStrokeField=null}function popup_searchTags(){fullPopupWindow("Search",server_url+"srv/searchtag?lang="+language+(null==ident?"":"&objid="+ident),360,210)}
function popup_refSearch(){var a=myKaMap.getCenter();uref=(new LatLng(a.lat,a.lon)).toUTMRef();popupwindow(myKaMap.domObj,"<h1>"+_("Show reference on map")+'</h1><form class="mapref"><span class="sleftlab">MGRS ref: </span><div><input id="locx" type="text" size="3" maxlength="3"><input id="locy" type="text" size="3" maxlength="3">&nbsp;<input type="button" id="butt_mgrs"   value="'+_("Find")+'">&nbsp;</div><hr><span class="sleftlab">UTM: </span><nobr><div><input id="utmz" type="text" size="2" maxlength="2" value="'+
uref.lngZone+'"><input id="utmnz" type="text" size="1" maxlength="1" value="'+uref.latZone+'">&nbsp;&nbsp<input id="utmx" type="text" size="6" maxlength="6"><input id="utmy" type="text" size="7" maxlength="7">&nbsp;<input type="button" id="butt_utm"   value="'+_("Find")+'" style="margin-right:3.5em">&nbsp;</div></nobr><hr><span class="sleftlab">LatLong: </span><nobr><div><input id="ll_Nd" type="text" size="2" maxlength="2">\u00b0&nbsp;<input id="ll_Nm" type="text" size="6" maxlength="6">\'&nbsp;N&nbsp;&nbsp;<input id="ll_Ed" type="text" size="2" maxlength="2">\u00b0&nbsp;<input id="ll_Em" type="text" size="6" maxlength="6">\'&nbsp;E&nbsp;<input type="button" id="butt_ll"   value="'+
_("Find")+'">&nbsp;</div></nobr><hr></form>',isMobile?20:50,isMobile?53:70,!1);autojump("utmz","utmnz");autojump("utmnz","utmx");autojump("utmx","utmy");autojump("locx","locy");autojump("ll_Nd","ll_Nm");autojump("ll_Nm","ll_Ed");autojump("ll_Ed","ll_Em");$("#butt_mgrs").click(function(){doRefSearchLocal($("#locx").val(),$("#locy").val())});$("#butt_utm").click(function(){doRefSearchUtm($("#utmx").val(),$("#utmy").val(),$("#utmnz").val(),$("#utmz").val())});$("#butt_ll").click(function(){doRefSearchDM($("#ll_Nd").val(),
$("#ll_Nm").val(),$("#ll_Ed").val(),$("#ll_Em").val())})}function showUTMstring(a){return a.substring(0,5)+'<span class="kartref">'+a.substring(5,8)+"</span>"+a.substring(8,13)+'<span class="kartref">'+a.substring(13,16)+"</span>"+a.substring(16)}function showDMstring(a){deg=Math.floor(a);minx=a-deg;0>a&&0!=minx&&(minx=1-minx);mins=Math.round(6E3*minx)/100;return""+deg+"\u00b0 "+mins+"'"}var skNames=new statkartName(statkartName_url);
function popup_searchNames(){function a(a){if(null!=a){var d=isMobile?document.getElementById("searchform"):document.getElementById("searchresult");null!=d&&(d.innerHTML=a,removePopup(),setTimeout(function(){popup(document.getElementById("anchor"),b,50,70,null)},1E3))}}var b=popupwindow(document.getElementById("anchor")," <div><h1>"+_("Find Location Name (Kartverket)")+'</h1><div id="searchform"><form>  Navn: <input type="text"  width="10" id="findname"/>  <input id="searchbutton" type="button" value="'+
_("Search")+'" /></form><br><div id="searchresult"></div></div></div>',50,70,null);$("#searchbutton").click(function(b){b=b?b:event?event:null;b.cancelBubble=!0;b.stopPropagation&&b.stopPropagation();skNames.doSearch($("#findname").val(),a)})}function popup_posInfoPix(a,b){var c=myKaMap.pixToGeo(a,b);popup_posInfo(new LatLng(c[1],c[0]))}function popup_posInfoXY(a,b){popup_posInfo(new LatLng(b,a))}var wps=new statkartWPS(statkartWPS_url);
function popup_posInfo(a,b){var c=""+a.toUTMRef(),c=showUTMstring(c),d=myKaMap.geoToPix(a.lng,a.lat);if(b)popupImage(myKaMap.domObj,d[0],d[1]);else if(c=popupwindow(myKaMap.domObj,'<span class="sleftlab">UTM:</span>'+c+'<br><nobr><span class="sleftlab">Latlong:</span>'+showDMstring(a.lat)+"N, "+showDMstring(a.lng)+'E<br></nobr><span class="sleftlab">Loc:</span>'+ll2Maidenhead(a.lat,a.lng)+'<div title="kilde: kartverket (WPS)" id="wpsresult"></div>',d[0],d[1],!0),statkartWPS_enable&&wps.doElevation(a,
function(a){if(a.terrain||a.placename||a.elevation){var b="";a.placename&&(b+='<span class="sleftlab">Sted:</span>'+a.placename+"<br>");b+='<span class="sleftlab">Terreng:</span>'+a.terrain+"<br>";a.elevation&&(b+='<span class="sleftlab">H\u00f8yde:</span>'+Math.round(a.elevation)+" moh<br>");document.getElementById("wpsresult").innerHTML=b}}),canUpdate()){var g=c.appendChild(document.createElement("hr"));g.style.marginBottom="0";g.style.marginTop="0.2em";c.appendChild(createItem(_("Add APRS object here"),
function(){popup_editObject(d[0],d[1]);menuMouseSelect()})).style.width="12em"}}function popup_setLanguage(){var a=new PopupMenu("language");a.clear();a.add("Norsk",function(){storage[uid+".language"]="no";LANGUAGE("no");menuMouseSelect()});a.add("English",function(){storage[uid+".language"]="en";LANGUAGE("en");menuMouseSelect()});a.activate(document.getElementById("anchor"),50,70)}var wx=new WXreport(WXreport_url);
function popup_wxInfoPix(a,b){var c=myKaMap.pixToGeo(a,b),c=new LatLng(c[1],c[0]);popup_wxInfo(c)}
function popup_wxInfo(a){var b=myKaMap.geoToPix(a.lng,a.lat);popupwindow(myKaMap.domObj,'<img title="Kilde: Meteorologisk institutt (met.no)" src="images/met.gif" align="right"><h3>V\u00e6rmelding fra met.no</h3><div id="wxresult"></div>',b[0],b[1],!1);wx.doTextReport(a,function(a){function b(a){return'<h4 head="wxhead">'+dateFormat(a.from,a.to)+" ("+a.name+")</h4>"+a.fcast}var g=b(a[0]),g=g+b(a[1]);isMobileApp||(g+=b(a[2]));document.getElementById("wxresult").innerHTML=g})}
function dateFormat(a,b){var c="",d="S\u00f8ndag Mandag Tirsdag Onsdag Torsdag Fredag L\u00f8rdag".split(" "),g=new Date,l=a.getHours(),h=b.getHours();10>l&&(l="0"+l);10>h&&(h="0"+h);c=d[a.getDay()];a.getDate()>g.getDate()&&0<a.getHours()&&(c=c+" kl."+l);if(b.getDate()>a.getDate()+1||0<b.getHours())c=0==b.getHours()?c+" til "+b.getDay()+"/"+d[b.getDay()-1]:c+" til "+(a.getDate()!=b.getDate()?d[b.getDay()]:"")+" kl. "+h;return c};function layerSwitcher(a){this.kaMap=a;this.storage=null}layerSwitcher.prototype.getSettings=function(){var a=storage[uid+".baselayer"];null!=a&&this.kaMap.setBaseLayerId(a);for(a=0;a<mapLayers.length;a++){var b=mapLayers[a].layer;if(!b.isBaseLayer&&b.displayInLayerSwitcher){var c=storage[uid+".layer."+b.name];b.setVisibility(null!=c&&"on"==c)}}};layerSwitcher.prototype.setBaseLayer=function(a){this.kaMap.olMap.setBaseLayer(mapLayers[a].layer);storage[uid+".baselayer"]=mapLayers[a].layer.id};
layerSwitcher.prototype.toggleOverlay=function(a){var b=mapLayers[a].layer.getVisibility();mapLayers[a].layer.setVisibility(!b);storage[uid+".layer."+mapLayers[a].layer.name]=b?"off":"on"};layerSwitcher.prototype.refreshOverlay=function(){for(var a=0;a<mapLayers.length;a++){var b=mapLayers[a].layer;!b.isBaseLayer&&"refresh"in b&&b.getVisibility()&&b.refresh()}};
layerSwitcher.prototype.evaluateLayers=function(){var a=-1;if(null!=mapLayers&&0<mapLayers.length){for(var b=0;b<mapLayers.length;b++){var c=mapLayers[b].predicate(),d=mapLayers[b].layer;d.displayInLayerSwitcher=c;d.isBaseLayer||d.setVisibility(c?"on"==storage[uid+".layer."+d.name]:!1);d.isBaseLayer&&d.getVisibility()&&(d.setVisibility(!1),c&&(a=b))}if(-1==a)for(b=0;b<mapLayers.length;b++){if(mapLayers[b].layer.isBaseLayer&&mapLayers[b].layer.displayInLayerSwitcher){this.kaMap.olMap.baseLayer=mapLayers[b].layer;
this.kaMap.olMap.events.triggerEvent("changebaselayer");mapLayers[b].layer.setVisibility(!0);break}}else mapLayers[a].layer.setVisibility(!0)}};
layerSwitcher.prototype.displayLayers=function(a,b){function c(a){return function(){h.setBaseLayer(a);setTimeout(function(){h.evaluateLayers();k.innerHTML=g();l()},100)}}function d(a){return function(){h.toggleOverlay(a)}}function g(){var a='<div id="layerSwitcher">';if(null!=mapLayers&&0<mapLayers.length){for(var a=a+("<h2>"+_("Base layer")+"</h2><form>"),b=0;b<mapLayers.length;b++)mapLayers[b].layer.displayInLayerSwitcher&&mapLayers[b].layer.isBaseLayer&&(a+='<input id="layer'+b+'" type="radio" name="layer" value="layer'+
b+'"',mapLayers[b].layer.getVisibility()&&(a+=" checked"),a+="> <span>"+mapLayers[b].layer.name+"</span><br>");a+="</form><h2>"+_("Overlays")+"</h2><form>";for(b=0;b<mapLayers.length;b++)!mapLayers[b].layer.isBaseLayer&&mapLayers[b].layer.displayInLayerSwitcher&&(a+='<input id="layer'+b+'" type="checkbox" name="overlay" value="layer'+b+'"',mapLayers[b].layer.getVisibility()&&(a+=" checked"),a+="> <span>"+mapLayers[b].layer.name+"</span><br>")}return a+"</form></div>"}function l(){for(var a=0;a<mapLayers.length;a++)mapLayers[a].layer.displayInLayerSwitcher&&
(mapLayers[a].layer.isBaseLayer?$("#layer"+a).click(c(a)):$("#layer"+a).click(d(a)))}var h=this,k=popupwindow(myKaMap.domObj,g(),a,b,null);l()};function LatLng(a,b){this.lat=a;this.lng=b;this.distance=LatLngDistance;this.toOSRef=LatLngToOSRef;this.toUTMRef=LatLngToUTMRef;this.WGS84ToOSGB36=WGS84ToOSGB36;this.OSGB36ToWGS84=OSGB36ToWGS84;this.toString=LatLngToString}function LatLngToString(){return"("+Math.round(100*this.lat)/100+", "+Math.round(100*this.lng)/100+")"}function OSRef(a,b){this.easting=a;this.northing=b;this.toLatLng=OSRefToLatLng;this.toString=OSRefToString;this.toSixFigureString=OSRefToSixFigureString}
function OSRefToString(){return"("+this.easting+", "+this.northing+")"}function OSRefToSixFigureString(){var a=Math.floor(this.easting/1E5),b=Math.floor(this.northing/1E5),c="",c=5>b?5>a?"S":"T":10>b?5>a?"N":"O":"H",d="",d=65+5*(4-b%5)+a%5;73<=d&&d++;var d=chr(d),a=Math.floor((this.easting-1E5*a)/100),b=Math.floor((this.northing-1E5*b)/100),g=a;100>a&&(g="0"+g);10>a&&(g="0"+g);a=b;100>b&&(a="0"+a);10>b&&(a="0"+a);return c+d+g+a}
function UTMRef(a,b,c,d){this.easting=a;this.northing=b;this.latZone=c;this.lngZone=d;this.toLatLng=UTMRefToLatLng;this.toString=UTMRefToString}function UTMRefToString(){return this.lngZone+this.latZone+" "+Math.round(this.easting)+" "+Math.round(this.northing)}function RefEll(a,b){this.maj=a;this.min=b;this.ecc=(a*a-b*b)/(a*a)}function sinSquared(a){return Math.sin(a)*Math.sin(a)}function cosSquared(a){return Math.cos(a)*Math.cos(a)}function tanSquared(a){return Math.tan(a)*Math.tan(a)}
function sec(a){return 1/Math.cos(a)}function deg2rad(a){return Math.PI/180*a}function rad2deg(a){return 180/Math.PI*a}function chr(a){a=a.toString(16);1==a.length&&(a="0"+a);return unescape("%"+a)}function ord(a){a=a.charAt(0);var b;for(b=0;256>b;++b){var c=b.toString(16);1==c.length&&(c="0"+c);c="%"+c;c=unescape(c);if(c==a)break}return b}
function LatLngDistance(a){var b=deg2rad(this.lat),c=deg2rad(a.lat),d=deg2rad(this.lng),g=deg2rad(a.lng);a=6366.707*Math.cos(d)*Math.sin(b);var d=6366.707*Math.sin(d)*Math.sin(b),b=6366.707*Math.cos(b),l=6366.707*Math.cos(g)*Math.sin(c),g=6366.707*Math.sin(g)*Math.sin(c),c=6366.707*Math.cos(c);return Math.sqrt((a-l)*(a-l)+(d-g)*(d-g)+(b-c)*(b-c))}
function OSGB36ToWGS84(){for(var a=new RefEll(6377563.396,6356256.909),b=a.maj,a=a.ecc,c=deg2rad(this.lat),d=deg2rad(this.lng),g=b/Math.sqrt(1-a*sinSquared(c)),b=(g+0)*Math.cos(c)*Math.cos(d),d=(g+0)*Math.cos(c)*Math.sin(d),a=((1-a)*g+0)*Math.sin(c),l=deg2rad(4.172222E-5),h=deg2rad(6.861111E-5),c=deg2rad(2.3391666E-4),g=446.448+.9999795106*b+-l*d+h*a,c=-124.157+c*b+.9999795106*d+-l*a,d=542.06+-h*b+l*d+.9999795106*a,a=new RefEll(6378137,6356752.3141),b=a.maj,a=a.ecc,l=rad2deg(Math.atan(c/g)),c=Math.sqrt(g*
g+c*c),h=Math.atan(d/(c*(1-a))),k=1;10>k;k++)g=b/Math.sqrt(1-a*sinSquared(h)),h=phiN1=Math.atan((d+a*g*Math.sin(h))/c);this.lat=rad2deg(h);this.lng=l}
function WGS84ToOSGB36(){for(var a=new RefEll(6378137,6356752.3141),b=a.maj,a=a.ecc,c=deg2rad(this.lat),d=deg2rad(this.lng),g=b/Math.sqrt(1-a*sinSquared(c)),b=(g+0)*Math.cos(c)*Math.cos(d),d=(g+0)*Math.cos(c)*Math.sin(d),a=((1-a)*g+0)*Math.sin(c),l=deg2rad(-4.172222E-5),h=deg2rad(-6.861111E-5),c=deg2rad(-2.3391666E-4),g=-446.448+1.0000204894*b+-l*d+h*a,c=124.157+c*b+1.0000204894*d+-l*a,d=-542.06+-h*b+l*d+1.0000204894*a,a=new RefEll(6377563.396,6356256.909),b=a.maj,a=a.ecc,l=rad2deg(Math.atan(c/g)),
c=Math.sqrt(g*g+c*c),h=Math.atan(d/(c*(1-a))),k=1;10>k;k++)g=b/Math.sqrt(1-a*sinSquared(h)),h=phiN1=Math.atan((d+a*g*Math.sin(h))/c);this.lat=rad2deg(h);this.lng=l}
function OSRefToLatLng(){var a=new RefEll(6377563.396,6356256.909),b=deg2rad(49),c=deg2rad(-2),d=a.maj,g=a.min,l=a.ecc,h=0,a=0,a=this.easting,k=this.northing,m=(d-g)/(d+g),n=0,h=(k- -1E5)/(.9996012717*d)+b;do n=.9996012717*g*((1+m+1.25*m*m+1.25*m*m*m)*(h-b)-(3*m+3*m*m+2.625*m*m*m)*Math.sin(h-b)*Math.cos(h+b)+(1.875*m*m+1.875*m*m*m)*Math.sin(2*(h-b))*Math.cos(2*(h+b))-35/24*m*m*m*Math.sin(3*(h-b))*Math.cos(3*(h+b))),h+=(k- -1E5-n)/(.9996012717*d);while(.001<=k- -1E5-n);b=.9996012717*d*Math.pow(1-l*
sinSquared(h),-.5);m=.9996012717*d*(1-l)*Math.pow(1-l*sinSquared(h),-1.5);g=b/m-1;d=Math.tan(h)/(2*m*b);l=Math.tan(h)/(24*m*Math.pow(b,3))*(5+3*tanSquared(h)+g-9*tanSquared(h)*g);k=Math.tan(h)/(720*m*Math.pow(b,5))*(61+90*tanSquared(h)+45*tanSquared(h)*tanSquared(h));g=sec(h)/b;m=sec(h)/(6*b*b*b)*(b/m+2*tanSquared(h));n=sec(h)/(120*Math.pow(b,5))*(5+28*tanSquared(h)+24*tanSquared(h)*tanSquared(h));b=sec(h)/(5040*Math.pow(b,7))*(61+662*tanSquared(h)+1320*tanSquared(h)*tanSquared(h)+720*tanSquared(h)*
tanSquared(h)*tanSquared(h));h=h-d*Math.pow(a-4E5,2)+l*Math.pow(a-4E5,4)-k*Math.pow(a-4E5,6);a=c+g*(a-4E5)-m*Math.pow(a-4E5,3)+n*Math.pow(a-4E5,5)-b*Math.pow(a-4E5,7);return new LatLng(rad2deg(h),rad2deg(a))}
function LatLngToOSRef(){var a=new RefEll(6377563.396,6356256.909),b=deg2rad(49),c=deg2rad(-2),d=a.maj,g=a.min,l=a.ecc,h=deg2rad(this.lat),a=deg2rad(this.lng),k=0,m=0,k=(d-g)/(d+g),m=.9996012717*d*Math.pow(1-l*sinSquared(h),-.5),l=.9996012717*d*(1-l)*Math.pow(1-l*sinSquared(h),-1.5),d=m/l-1,g=.9996012717*g*((1+k+1.25*k*k+1.25*k*k*k)*(h-b)-(3*k+3*k*k+2.625*k*k*k)*Math.sin(h-b)*Math.cos(h+b)+(1.875*k*k+1.875*k*k*k)*Math.sin(2*(h-b))*Math.cos(2*(h+b))-35/24*k*k*k*Math.sin(3*(h-b))*Math.cos(3*(h+b)))+
-1E5,k=m/2*Math.sin(h)*Math.cos(h),n=m/24*Math.sin(h)*Math.pow(Math.cos(h),3)*(5-tanSquared(h)+9*d),u=m/720*Math.sin(h)*Math.pow(Math.cos(h),5)*(61-58*tanSquared(h)+Math.pow(Math.tan(h),4)),b=m*Math.cos(h),l=m/6*Math.pow(Math.cos(h),3)*(m/l-tanSquared(h)),h=m/120*Math.pow(Math.cos(h),5)*(5-18*tanSquared(h)+Math.pow(Math.tan(h),4)+14*d-58*tanSquared(h)*d),m=g+k*Math.pow(a-c,2)+n*Math.pow(a-c,4)+u*Math.pow(a-c,6),k=4E5+b*(a-c)+l*Math.pow(a-c,3)+h*Math.pow(a-c,5);return new OSRef(k,m)}
function UTMRefToLatLng(){var a=new RefEll(6378137,6356752.314),b=a.maj,a=a.ecc,c=a/(1-a),d=(1-Math.sqrt(1-a))/(1+Math.sqrt(1-a)),g=this.easting-5E5,l=this.northing,h=6*(this.lngZone-1)-180+3;0>ord(this.latZone)-ord("N")&&(l-=1E7);var l=l/.9996/(b*(1-a/4-3*a*a/64-5*Math.pow(a,3)/256)),d=l+(3*d/2-27*Math.pow(d,3)/32)*Math.sin(2*l)+(21*d*d/16-55*Math.pow(d,4)/32)*Math.sin(4*l)+151*Math.pow(d,3)/96*Math.sin(6*l),l=b/Math.sqrt(1-a*Math.sin(d)*Math.sin(d)),k=Math.tan(d)*Math.tan(d),m=c*Math.cos(d)*Math.cos(d),
g=g/(.9996*l);return new LatLng(180/Math.PI*(d-l*Math.tan(d)/(b*(1-a)/Math.pow(1-a*Math.sin(d)*Math.sin(d),1.5))*(g*g/2-(5+3*k+10*m-4*m*m-9*c)*Math.pow(g,4)/24+(61+90*k+298*m+45*k*k-252*c-3*m*m)*Math.pow(g,6)/720)),h+(g-(1+2*k+m)*Math.pow(g,3)/6+(5-2*m+28*k-3*m*m+8*c+24*k*k)*Math.pow(g,5)/120)/Math.cos(d)*(180/Math.PI))}
function LatLngToUTMRef(a,b){var c=new RefEll(6378137,6356752.314),d=c.maj,g=c.ecc,l=this.lng,c=this.lat,h=Math.PI/180*c,k=Math.PI/180*l,m=Math.floor((l+180)/6)+1;56<=c&&64>c&&3<=l&&12>l&&(m=32);72<=c&&84>c&&(0<=l&&9>l?m=31:9<=l&&21>l?m=33:21<=l&&33>l?m=35:33<=l&&42>l&&(m=37));null!=b&&(m=b);var n=Math.PI/180*(6*(m-1)-180+3),l=getUTMLatitudeZoneLetter(c);null!=a&&(l=a);var u=g/(1-g),q=d/Math.sqrt(1-g*Math.sin(h)*Math.sin(h)),t=Math.tan(h)*Math.tan(h),v=u*Math.cos(h)*Math.cos(h),n=Math.cos(h)*(k-n),
k=.9996*q*(n+(1-t+v)*Math.pow(n,3)/6+(5-18*t+t*t+72*v-58*u)*Math.pow(n,5)/120)+5E5,d=.9996*(d*((1-g/4-3*g*g/64-5*g*g*g/256)*h-(3*g/8+3*g*g/32+45*g*g*g/1024)*Math.sin(2*h)+(15*g*g/256+45*g*g*g/1024)*Math.sin(4*h)-35*g*g*g/3072*Math.sin(6*h))+q*Math.tan(h)*(n*n/2+(5-t+9*v+4*v*v)*Math.pow(n,4)/24+(61-58*t+t*t+600*v-330*u)*Math.pow(n,6)/720));0>c&&(d+=1E7);return new UTMRef(k,d,l,m)}
function getOSRefFromSixFigureReference(a){var b=a.substring(0,1),c=a.substring(1,2),d=100*parseInt(a.substring(2,5),10);a=100*parseInt(a.substring(5,8),10);"H"==b?a+=1E6:"N"==b?a+=5E5:"O"==b?(a+=5E5,d+=5E5):"T"==b&&(d+=5E5);b=ord(c);73<b&&b--;return new OSRef(d+(b-65)%5*1E5,a+1E5*(4-Math.floor((b-65)/5)))}
function getUTMLatitudeZoneLetter(a){return 84>=a&&72<=a?"X":72>a&&64<=a?"W":64>a&&56<=a?"V":56>a&&48<=a?"U":48>a&&40<=a?"T":40>a&&32<=a?"S":32>a&&24<=a?"R":24>a&&16<=a?"Q":16>a&&8<=a?"P":8>a&&0<=a?"N":0>a&&-8<=a?"M":-8>a&&-16<=a?"L":-16>a&&-24<=a?"K":-24>a&&-32<=a?"J":-32>a&&-40<=a?"H":-40>a&&-48<=a?"G":-48>a&&-56<=a?"F":-56>a&&-64<=a?"E":-64>a&&-72<=a?"D":-72>a&&-80<=a?"C":"Z"};function FilterProfile(){this.sFilter=storage[uid+".filter"];this.done=this.initialized=!1;this.filterMenu=null;this.init()}FilterProfile.prototype.selectedProf=function(){return this.sFilter};FilterProfile.prototype.selectProfile=function(a){a==this.sFilter&&this.done||(this.sFilter=a,this.done&&(storage[uid+".filter"]=a,myOverlay.removePoint(),mapupdate_subscribe()),this.updateMenu())};
FilterProfile.prototype.updateMenu=function(){for(var a in filterViews)if(filterViews[a].name==this.sFilter){$("div#filterChoice").html(filterViews[a].title);break}};
FilterProfile.prototype.init=function(){var a=this;if(!a.done){var b=args.view;b&&(a.sFilter=b);null==a.sFilter&&(a.sFilter=defaultFilterView);a.done||ctxtMenu.addCallback("FILTERS",function(b){for(var d in filterViews){var g=filterViews[d];g.name&&1<g.name.length&&(!g.restricted||isLoggedIn())&&b.add(g.title,function(b){a.selectProfile(b)},g.name)}});addContextMenu("filterMenu","FILTERS");a.selectProfile(a.sFilter);a.done=!0}};var myKaMap=null,myKaNavigator=null,myKaQuery=null,myScalebar=null,queryParams=null,myKaRuler=null,objectClickable=!1,myKaRubberZoom=null,myKaTracker=null,initialized=!1,win1=null,eventz=null,clientses=0,geopos,isOpera=_BrowserIdent_isOpera(),isIframe=!1,isMobile=!1,isMobileApp=!1,storage=null,ses_storage=null,uid=null,myCoordinates=myOverlay=myInterval=null,filterProfiles=null,layers;layers=new layerSwitcher(myKaMap);
function myOnLoad_iframe(){isIframe=!0;startUp();var a=document.getElementById("refToggler");toggleReference(a)}function myOnLoad(){startUp()}function myOnLoad_mobile(){isMobile=!0;startUp();var a=document.getElementById("refToggler");toggleReference(a)}window.onbeforeunload=function(){message_close();mapupdate_close()};
function startUp(){var a=getQueryParam("map"),b=getQueryParam("extents"),c=getQueryParam("cps");initDHTMLAPI();myKaMap=new kaMap("PolaricVP");layers=new layerSwitcher(myKaMap);myKaRuler=new myKaRuler(myKaMap);myKaQuery=new kaQuery(myKaMap,KAMAP_POINT_QUERY);myKaRubberZoom=new kaRubberZoom(myKaMap);myKaTracker=new kaMouseTracker(myKaMap);myKaTracker.activate();myKaNavigator=new kaNavigator(myKaMap);myKaNavigator.activate();myScalebar=new ScaleBar(1);myScalebar.divisions=3;myScalebar.subdivisions=2;
myScalebar.minWidth=150;myScalebar.maxWidth=250;myScalebar.place("scalebar");myKaMap.registerForEvent(KAMAP_MAP_INITIALIZED,null,myMapInitialized);myKaMap.registerForEvent(KAMAP_ERROR,null,myMapError);myKaMap.registerForEvent(KAMAP_INITIALIZED,null,myInitialized);myKaMap.registerForEvent(KAMAP_SCALE_CHANGED,null,myScaleChanged);myKaMap.registerForEvent(KAMAP_EXTENTS_CHANGED,null,myExtentChanged);myKaMap.registerForEvent(KAMAP_LAYERS_CHANGED,null,myLayersChanged);myKaMap.registerForEvent(KAMAP_LAYER_STATUS_CHANGED,
null,myLayersChanged);myKaMap.registerForEvent(KAMAP_QUERY,null,myQuery);myKaMap.registerForEvent(KAMAP_MAP_CLICKED,null,myMapClicked);isMobileApp||myKaMap.registerForEvent(KAMAP_MOUSE_TRACKER,null,myMouseMoved);myKaMap.registerForEvent(KAMAP_MOVE_START,null,function(){null!=myOverlay&&myOverlay.removePointExcept("my_.*")});storage=window.localStorage;null==storage&&(storage={getItem:function(a){return null},removeItem:function(a){return null},setItem:function(a,b){return null}});ses_storage=window.sessionStorage;
null==ses_storage&&(ses_storage={getItem:function(a){return null},removeItem:function(a){return null},setItem:function(a,b){return null}});setSesStorage(ses_storage);isMobileApp&&getViewportRes();myKaMap.initialize(a,b,c);geopos=document.getElementById("geoPosition");window.onresize=function(){myKaMap.drawPage()};myKaMap.drawPage()}var permalink=!1,args=null;
function myMapInitialized(){var a=a=window.location.href,a=a.substring(a.indexOf("?")+1,a.length);args={};for(var b=a.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("=");if(-1!=d){var g=b[c].substring(0,d),d=b[c].substring(d+1);args[g]=unescape(d)}}uid=args.uid;uid=null==uid?"polaric":"polaric."+uid;init_labelStyle(storage,uid);OpenLayers.Console.info("UID=",uid);(permalink=2<=a.length&&a.match(/.*zoom\=.*/)&&a.match(/.*lat\=.*/))||layers.getSettings()}function myMapError(a){alert(a)}
var ststate=null;
function myInitialized(){sar_key=storage["polaric.sarkey"];var a=null;null==a&&(a=args.view);null==a&&(a=defaultView);if(!permalink){var b=storage[uid+".extents.0"],c=storage[uid+".extents.1"],d=storage[uid+".extents.2"],g=storage[uid+".extents.3"];null!=b?myKaMap.zoomToExtents(parseFloat(b),parseFloat(c),parseFloat(d),parseFloat(g)):myKaMap.selectMap(a,!1)}$("#layerSelect").on("click contextmenu",function(a){a=a?a:event?event:null;layers.displayLayers(a.pageX?a.pageX:a.clientX,32);a.cancelBubble=
!0;return!1});var l=myKaMap.getMaps();ctxtMenu.addCallback("AREASELECT",function(a){for(var b in l)l[b]&&l[b].name&&1<l[b].name.length&&!l[b].hidden&&a.add(l[b].title,function(a){myKaMap.selectMap(a,!1)},l[b].name)});addContextMenu("areaSelect","AREASELECT");null==myOverlay&&(myOverlay=new kaXmlOverlay(myKaMap,1200));myOverlay.registerForEvent(XMLOVERLAY_ERROR,null,postLoadXml_Fail);myOverlay.registerForEvent(XMLOVERLAY_LOAD,null,postLoadXml);filterProfiles=new FilterProfile;null!=args.filter&&filterProfiles.selectProfile(args.filter);
null!=args.findcall&&findItem(args.findcall,!1);null!=args.track&&(findItem(args.track,!1),toggleTracked(args.track));null!=args.gotopos&&(b=args.gotopos.split(","),a=parseFloat(b[0]),b=parseFloat(b[1]),gotoPos(a,b,!0));null!=args.scale&&(a=parseInt(args.scale,10),isNaN(a)||myKaMap.zoomToScale(a));isMobileApp?null==storage[uid+".language"]&&navigator.globalization.getPreferredLanguage(function(a){alert("language: "+a.value+"\n");storage[uid+".language"]=a.value},function(){popup_setLanguage()}):null!=
args.lang&&(storage[uid+".language"]=args.lang);a=storage[uid+".language"];null!=a&&LANGUAGE(a);switchMode("toolPan");isMobile&&(document.getElementById("geoPosition").ontouchend=function(a){null!=gpsTracker&&gpsTracker.toggleSpeedDisplay()});addContextMenu("buttonMenu","MAIN");a=myKaMap.olMap.getViewport();a.onmousedown=menuMouseSelect;a.oncontextmenu=function(a){a=a?a:event?event:null;document.kaCurrentTool!=myKaRuler&&ctxtMenu.show(null,a);a.cancelBubble=!0};document.getElementById("toolbar").oncontextmenu=
function(a){a=a?a:event?event:null;a.cancelBubble=!0};ie?(a.onclick=function(a){document.kaCurrentTool!=myKaQuery&&menuMouseSelect()},document.getElementById("toolbar").onclick=function(a){a=a?a:event?event:null;document.kaCurrentTool!=myKaQuery&&menuMouseSelect();a.cancelBubble=!0}):(a.onmouseup=function(a){menuMouseSelect()},document.getElementById("toolbar").onmouseup=function(a){isMenu&&menuMouseSelect();a.cancelBubble=!0});initialized=!0;message_init();mapupdate_init();isIframe||isMobile||ses_storage["polaric.welcomed"]||
(ses_storage["polaric.welcomed"]=!0,setTimeout(function(){welcome()},2E3))}function welcome(){remotepopupwindowCSS(myKaMap.domObj,"welcome.html",1,1,"welcome")}function roundDeg(a){return Math.round(1E3*a)/1E3}var xmlSeqno=0,retry=0,lastXmlCall=0;function sarUrl(){return server_url+(null==sar_key?"":"sar_"+sar_key+"/")}function postLoadXml_Fail(){OpenLayers.Console.warn("XML Call: Not found");null!=sar_key&&(alert(_("Access to SAR info denied. Invalid key")),removeSarKey(),show_SAR_access(!1))}
function postLoadXml(){retry=0;null!=myOverlay.meta.clientses&&(clientses=myOverlay.meta.clientses);document.getElementById("sarmode").style.visibility=null!=myOverlay.meta.sarmode&&"true"==myOverlay.meta.sarmode?"visible":"hidden";filterProfiles.init();show_SAR_access(null!=getLogin());isIframe||isMobile||isMobileApp||null==getLogin()||(ldiv=document.getElementById("login"),ldiv.innerHTML=getLogin(),ldiv.className="login")}var currentScale=-1;
function myScaleChanged(a,b){b=Math.round(b);if(b!=currentScale){OpenLayers.Console.info("SCALE CHANGED: ",b);currentScale=b;myScalebar.update(b);1E3<=b&&(b=100*Math.round(b/100));1E4<=b&&(b=1E3*Math.round(b/1E3));1E6<=b?(b=1E5*Math.round(b/1E5),b=b/1E6+" Million"):1E4<=b&&(b=Math.round(b/1E3)+" 000");var c="current scale  1 : "+b;getRawObject("scale").innerHTML=c}}var prev_extents=null;
function myExtentChanged(a,b){if(null==prev_extents||roundDeg(b[0])!=roundDeg(prev_extents[0])||roundDeg(b[1])!=roundDeg(prev_extents[1])||roundDeg(b[2])!=roundDeg(prev_extents[2])||roundDeg(b[3])!=roundDeg(prev_extents[3]))OpenLayers.Console.info("EXTENTS CHANGED: ",b),initialized&&(storage[uid+".extents.0"]=roundDeg(b[0]).toString(),storage[uid+".extents.1"]=roundDeg(b[1]).toString(),storage[uid+".extents.2"]=roundDeg(b[2]).toString(),storage[uid+".extents.3"]=roundDeg(b[3]).toString()),setTimeout(function(){layers.evaluateLayers()},
10),initialized&&(setTimeout(function(){mapupdate_subscribe()},10),myKaMap.updateObjects()),prev_extents=b;myKaRuler.reset();myScaleChanged(null,myKaMap.getCurrentScale())}function myLayersChanged(a,b){initialized&&mapupdate_subscribe();layers.refreshOverlay()}function myQuery(a,b,c){menuMouseSelect()&&popup_posInfoXY(c[0],c[1]);return!1}function myMapClicked(a,b){return!0}
function myMouseMoved(a,b){var c=new LatLng(b.y,b.x);c.toUTMRef();var d=geopos,g=c.toUTMRef()+"<br>"+ll2Maidenhead(c.lat,c.lng)+'&nbsp;<span class="latlng">';latD=Math.floor(Math.abs(c.lat));lonD=Math.floor(Math.abs(c.lng));d.innerHTML=g+(latD+"\u00b0 "+Math.round(60*(Math.abs(c.lat)-latD))+"' "+(0>c.lat?"S ":"N ")+"&nbsp;"+lonD+"\u00b0 "+Math.round(60*(Math.abs(c.lng)-lonD))+"' "+(0>c.lng?"W":"E"))+"</span>"}
function myObjectClicked(a,b,c,d){b=b?b:event?event:null;var g=b.pageX?b.pageX:b.clientX,l=b.pageY?b.pageY:b.clientY;menuMouseSelect();c?setTimeout(function(){displayLink(c,d,g,l)},100):popup_stationInfo(a,!1,g,l);b.cancelBubble=!0;return!1}function displayLink(a,b,c,d){/^(p|P):.*/.test(a)?popupwindow(myKaMap.domObj,'<h1 class="popupimg">'+b+'</h1><img class="popupimg" src="'+a.substring(2)+'">',c,d,null,"obj_click",!0):isMobileApp||(window.location=a)}
function myTrailClicked(a,b){b=b?b:event?event:null;var c=b.pageX?b.pageX:b.clientX,d=b.pageY?b.pageY:b.clientY;menuMouseSelect();ie?remotepopupwindow(myKaMap.domObj,server_url+"srv/trailpoint?ajax=true&id="+a+"&time="+b.srcElement._time+"&lang="+language,c,d):remotepopupwindow(myKaMap.domObj,server_url+"srv/trailpoint?ajax=true&id="+a+"&time="+b.target._time+"&lang="+language,c,d);b.cancelBubble=!0;b.stopPropagation&&b.stopPropagation();return!1}
function histList_hover(a,b){var c=document.getElementById(a+"_"+b+"_trail");null!=c&&c.setAttribute("class","trailPoint_hover")}function histList_hout(a,b){var c=document.getElementById(a+"_"+b+"_trail");null!=c&&c.setAttribute("class","trailPoint")}function parsePosPix(a){a=a.substr(0,a.length()-2);return safeParseInt(a)}
function histList_click(a,b){function c(a){a=a.substr(0,a.length-2);return safeParseInt(a)}var d=document.getElementById(a+"_"+b+"_trail");menuMouseSelect();d.setAttribute("class","trailPoint");var g=d.parentNode,l=c(d.style.left)+c(g.style.left)+c(g.parentNode.style.left)+10,d=c(d.style.top)+c(g.style.top)+c(g.parentNode.style.top)+10;remotepopupwindow(myKaMap.domObj,server_url+"srv/trailpoint?ajax=true&id="+a+"&index="+b+"&lang="+language,l,d)}
function ll2Maidenhead(a,b){var c=b+180,d=chr(65+Math.floor(c/20)),g=a+90,l=chr(65+Math.floor(g/10)),c=chr(48+Math.floor(c%20/2)),g=chr(48+Math.floor(g%10)),h=chr(97+Math.floor((b+180)%2*12)),k=chr(97+Math.floor((a+90)%1*24));return d+l+c+g+h+k}function parseQueryString(){queryParams={};var a=window.location.search;if(""!=a)for(var a=a.substring(1),a=a.split("&"),b=0;b<a.length;b++){var c=a[b].split("=");queryParams[c[0]]=c[1]}}
function getQueryParam(a){queryParams||parseQueryString();return queryParams[a]?queryParams[a]:""}function mySetMap(a){window.storage[uid+".view"]=a;myKaMap.selectMap(a)}
function toggleToolbar(a){""==a.style.backgroundImage&&(a.isOpen=!0);if(a.isOpen){a.title="show toolbar";a.style.backgroundImage="url("+server_url+"KaMap/images/arrow_down.png)";getObjectTop(a);var b=getObject("toolbar");b.display="none";a.isOpen=!1;a.style.top="3px"}else a.title="hide toolbar",a.style.backgroundImage="url("+server_url+"KaMap/images/arrow_up.png)",b=getObject("toolbar"),b.display="block",a.isOpen=!0,b=getObjectHeight("toolbar"),a.style.top=b+3+"px"}
function toggleReference(a){""==a.style.backgroundImage&&(a.isOpen=!0);if(a.isOpen){a.title="show reference";a.style.backgroundImage="url("+server_url+"KaMap/images/arrow_up.png)";var b=getObject("reference");b.display="none";a.isOpen=!1;a.style.bottom="8px"}else a.title="hide reference",a.style.backgroundImage="url("+server_url+"KaMap/images/arrow_down.png)",b=getObject("reference"),b.display="block",a.isOpen=!0,a.style.bottom=getObjectHeight("reference")+5+"px"}
function switchMode(a){isIframe||isMobile||"toolRuler"!=a?"toolQuery"==a?(myKaQuery.activate(),objectClickable=!0,isIframe||isMobile||(getRawObject("toolRuler").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/ruler1.gif)"),getRawObject("toolQuery").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/tool_query_2.png)",getRawObject("toolPan").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/tool_pan_1.png)",getRawObject("toolZoomRubber").style.backgroundImage=
"url("+server_url+"KaMap/images/icon_set_nomad/tool_rubberzoom_1.png)"):"toolPan"==a?(myKaNavigator.activate(),objectClickable=!0,isIframe||isMobile||(getRawObject("toolRuler").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/ruler1.gif)"),getRawObject("toolQuery").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/tool_query_1.png)",getRawObject("toolPan").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/tool_pan_2.png)",getRawObject("toolZoomRubber").style.backgroundImage=
"url("+server_url+"KaMap/images/icon_set_nomad/tool_rubberzoom_1.png)"):"toolZoomRubber"==a?(myKaRubberZoom.activate(),objectClickable=!1,isIframe||isMobile||(getRawObject("toolRuler").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/ruler1.gif)"),getRawObject("toolQuery").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/tool_query_1.png)",getRawObject("toolPan").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/tool_pan_1.png)",getRawObject("toolZoomRubber").style.backgroundImage=
"url("+server_url+"KaMap/images/icon_set_nomad/tool_rubberzoom_2.png)"):(myKaNavigator.activate(),objectClickable=!0):(myKaRuler.activate(),objectClickable=!1,getRawObject("toolRuler").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/ruler2.gif)",getRawObject("toolQuery").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/tool_query_1.png)",getRawObject("toolPan").style.backgroundImage="url("+server_url+"KaMap/images/icon_set_nomad/tool_pan_1.png)",getRawObject("toolZoomRubber").style.backgroundImage=
"url("+server_url+"KaMap/images/icon_set_nomad/tool_rubberzoom_1.png)")};
