function setStatus(a){geopos.innerHTML=a}var viewportTab=['<meta name="viewport" content="target-densitydpi=device-dpi*1.5 width=device-width, height=device-height">','<meta name="viewport" content="target-densitydpi=device-dpi width=device-width, height=device-height">'],viewportDescr=["1.5 X (standard)","1.0 X ("+_("high resolution")+")"];
function switchViewportRes(){var a=parseInt(storage["polaric.viewportIndex"],10),a=(a+1)%2;isNaN(a)&&(a=0);alert(_("Magnification")+": "+viewportDescr[a]);storage["polaric.viewportIndex"]=a.toString();location.reload()}function getViewportRes(){var a=parseInt(storage["polaric.viewportIndex"],10);$("head").append(viewportTab[a])}
function myOnLoad_droid(){function a(a){menuMouseSelect();a.cancelBubble=!0}isMobile=isMobileApp=!0;document.addEventListener("deviceready",function(){document.addEventListener("menubutton",function(a){return popupActive()?menuMouseSelect():showContextMenu(document.getElementById("toolbar"),a,"MAIN")},!1);startUp();var a=document.getElementById("refToggler");toggleReference(a);setStatus("&nbsp; "+_("PolaricDroid app ready"))},!1);window.addEventListener("orientationchange",function(){location.reload(!1)});
onPopup(function(){document.addEventListener("backbutton",a,!1)},function(){document.removeEventListener("backbutton",a,!1)})};GpsTracker=function(){this.gps_on=!1;this.watchID=this.my_point=null;this.speedDisplay=0};
GpsTracker.prototype.activate=function(){function a(c){e=0;if(60<c.coords.accuracy)null!=b.my_point&&(b.my_point.removeFromMap(),b.my_point=null),setStatus("&nbsp; "+_("GPS inaccurate position")+" ("+c.coords.accuracy+" m)");else{var a=new LatLng(c.coords.latitude,c.coords.longitude),d=a.toUTMRef();myKaMap.zoomToGeo(a.lng,a.lat,.2);0<b.speedDisplay?setStatus('<div id="speedDisplay">'+f(c.coords)+"</div>"):setStatus("&nbsp; "+_("GPS position ok")+"<br>"+d+"&nbsp;/&nbsp;"+f(c.coords));null==b.my_point?
(b.my_point=myOverlay.addNewPoint("my_gps_position",a.lng,a.lat),c=new kaXmlIcon,c.setImage(b.my_point,"images/position.png",60,60),b.my_point.addGraphic(c),b.my_point.div.appendChild(c.ldiv),c.setClass("gpsposition")):b.my_point.setPosition(a.lng,a.lat);myKaMap.updateObjects()}}function g(a){null!=b.watchID&&(a.code==PositionError.TIMEOUT?setStatus("&nbsp; "+_("waiting for GPS...")+"<br>"):(a.code=PositionError.POSITION_UNAVAILABLE)?3<=e++?(navigator.geolocation.clearWatch(this.watchID),setTimeout(d,
2E4)):(e=0,setStatus("&nbsp; "+_("Position not available")+"<br>"),navigator.notification.alert(_("ERROR: Position is not available"),null,"PolaricDroid"),b.deactivate()):(setStatus("&nbsp; "+_("GPS not available")+"<br>"+a.message),navigator.notification.alert(_("ERROR: No access to GPS. Check your settings."),null,"PolaricDroid"),b.deactivate()))}function f(a){var d="",d=22>a.heading||337<a.heading?"N":67>a.heading?"NE":112>a.heading?"E":157>a.heading?"SE":202>a.heading?"S":247>a.heading?"SW":292>
a.heading?"W":"NW";return 2==b.speedDisplay?'<span class="speed">'+Math.round(19.4384449*a.speed)/10+"</span> "+_("knots")+" "+d:'<span class="speed">'+Math.round(3.6*a.speed)+"</span> km/h "+d}function d(){b.watchID=navigator.geolocation.watchPosition(a,g,{timeout:6E4,enableHighAccuracy:!0,maximumAge:1E4})}var b=this,e=0;b.gps_on=!0;null==b.watchID&&d();setStatus("&nbsp; "+_("GPS <u>on</u>"))};GpsTracker.prototype.isActive=function(){return null!=this.watchID};
GpsTracker.prototype.deactivate=function(){this.gps_on=!1;myOverlay.removePoint("my_gps_position");this.my_point=null;navigator.geolocation.clearWatch(this.watchID);this.watchID=null;setStatus("&nbsp; "+_("GPS <u>off</u>"));myKaMap.updateObjects()};
GpsTracker.prototype.toggleSpeedDisplay=function(){this.speedDisplay=(this.speedDisplay+1)%3;1==this.speedDisplay?setStatus("&nbsp; "+_("Show <u>speed</u> (km/h): please wait...")):2==this.speedDisplay?setStatus("&nbsp; "+_("Show <u>speed</u> (knots): please wait...")):this.gps_on?setStatus("&nbsp; "+_("GPS <u>on</u>")):setStatus("&nbsp; "+_("GPS <u>off</u>"))};
