function _eventManager(){this.events=[];this.lastEventID=0}_eventManager.prototype.registerEventID=function(a){new String(a);this.events[a]||(this.events[a]=[])};_eventManager.prototype.registerForEvent=function(a,b,c){new String(a);this.events[a].push([b,c])};_eventManager.prototype.deregisterForEvent=function(a,b,c){new String(a);var e=!1;if(!this.events[a])return!1;for(var d=0;d<this.events[a].length;d++)this.events[a][d][0]==b&&this.events[a][d][1]==c&&(this.events[a].splice(d,1),e=!0);return e};
_eventManager.prototype.triggerEvent=function(a){new String(a);if(!this.events[a])return!1;for(b=1;b<arguments.length;b++);for(var b=0;b<this.events[a].length;b++)this.events[a][b][1].apply(this.events[a][b][0],arguments);return!0};var isCSS,isW3C,isIE4,isNN4;function initDHTMLAPI(){document.images&&(isW3C=(isCSS=document.body&&document.body.style?!0:!1)&&document.getElementById?!0:!1,isIE4=isCSS&&document.all?!0:!1,isNN4=document.layers?!0:!1,isIE6CSS=document.compatMode&&0<=document.compatMode.indexOf("CSS1")?!0:!1)}function seekLayer(a,b){for(var c,e=0;e<a.layers.length;e++){if(a.layers[e].name==b){c=a.layers[e];break}0<a.layers[e].document.layers.length&&(c=seekLayer(document.layers[e].document,b))}return c}
function getRawObject(a){var b;"string"==typeof a?isW3C?b=document.getElementById(a):isIE4?b=document.all(a):isNN4&&(b=seekLayer(document,a)):b=a;return b}function getObject(a){(a=getRawObject(a))&&isCSS&&(a=a.style);return a}function shiftTo(a,b,c){if(a=getObject(a))if(isCSS){var e="string"==typeof a.left?"px":0;a.left=b+e;a.top=c+e}else isNN4&&a.moveTo(b,c)}
function shiftBy(a,b,c){var e=getObject(a);if(e)if(isCSS){var d="string"==typeof e.left?"px":0;e.left=getObjectLeft(a)+b+d;e.top=getObjectTop(a)+c+d}else isNN4&&e.moveBy(b,c)}function setZIndex(a,b){var c=getObject(a);c&&(c.zIndex=b)}function setBGColor(a,b){var c=getObject(a);c&&(isNN4?c.bgColor=b:isCSS&&(c.backgroundColor=b))}function show(a){if(a=getObject(a))a.visibility="visible"}function hide(a){if(a=getObject(a))a.visibility="hidden"}
function getObjectLeft(a){a=getRawObject(a);var b=0;document.defaultView?b=document.defaultView.getComputedStyle(a,"").getPropertyValue("left"):a.currentStyle?b=a.currentStyle.left:a.style?b=a.style.left:isNN4&&(b=a.left);return parseInt(b)}function getObjectTop(a){a=getRawObject(a);var b=0;document.defaultView?b=document.defaultView.getComputedStyle(a,"").getPropertyValue("top"):a.currentStyle?b=a.currentStyle.top:a.style?b=a.style.top:isNN4&&(b=a.top);return parseInt(b)}
function getObjectWidth(a){a=getRawObject(a);var b=0;a.offsetWidth?b=a.offsetWidth:a.clip&&a.clip.width?b=a.clip.width:a.style&&a.style.pixelWidth&&(b=a.style.pixelWidth);return parseInt(b)}function getObjectHeight(a){a=getRawObject(a);var b=0;a.offsetHeight?b=a.offsetHeight:a.clip&&a.clip.height?b=a.clip.height:a.style&&a.style.pixelHeight&&(b=a.style.pixelHeight);return parseInt(b)}
function getInsideWindowWidth(){return window.innerWidth?window.innerWidth:isIE6CSS?document.body.parentElement.clientWidth:document.body&&document.body.clientWidth?document.body.clientWidth:0}function getInsideWindowHeight(){return window.innerHeight?window.innerHeight:isIE6CSS?document.body.parentElement.clientHeight:document.body&&document.body.clientHeight?document.body.clientHeight:0};var aXmlHttp=[],aXmlResponse=[];
function xmlResult(){for(var a=0;a<aXmlHttp.length;a++)if(aXmlHttp[a]&&aXmlHttp[a][0]&&4==aXmlHttp[a][0].readyState){var b=aXmlHttp[a][2],c=aXmlHttp[a][1],e="",d=404;try{e=aXmlHttp[a][0].responseText,d=aXmlHttp[a][0].status}catch(f){OpenLayers.Console.warning("Cannot access response from Ajax call (probably IE specific)")}aXmlHttp[a][0]=null;aXmlHttp[a][1]=null;aXmlHttp[a]=null;200==d?b.apply(c,Array(e)):404==d?b.apply(c,null):(OpenLayers.Console.info("xmlResult: status",d),503==d&&setTimeout(function(){window.location.reload()},
25E3))}}function abortCall(a){null!=aXmlHttp[a]&&null!=aXmlHttp[a][0]&&aXmlHttp[a][0].abort()}
function call(a,b,c){var e="GET",d="";4==arguments.length&&(e="POST",d=a.split(/\?/),a=d[0],d=d[1],null==d&&(d="empty"));for(var f=aXmlHttp.length,k=0;k<f;k++)if(null==aXmlHttp[k]){f=k;break}aXmlHttp[f]=Array(2);aXmlHttp[f][0]=getXMLHTTP();aXmlHttp[f][1]=b;aXmlHttp[f][2]=c;aXmlHttp[f][3]=a;aXmlHttp[f]&&(aXmlHttp[f][0].open(e,a,!0),aXmlHttp[f][0].onreadystatechange=xmlResult,"POST"==e?(aXmlHttp[f][0].setRequestHeader("Content-Type","application/x-www-form-urlencoded"),aXmlHttp[f][0].send(d)):"GET"==
e&&aXmlHttp[f][0].send(null));return f}function getXMLHTTP(){var a=null;a||"undefined"==typeof XMLHttpRequest||(a=new XMLHttpRequest);if(!a)try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(b){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(c){a=null}}return a};function cancelBubble(a){a=a?a:window.event;a.stopPropagation&&a.stopPropagation();null!=a.cancelBubble&&(a.cancelBubble=!0)}function touchHandler(){this.tstate=null;this.moving=this.cMenu=!1;this.starty=this.startx=0}
touchHandler.prototype.handle=function(a){function b(a,b){var c=document.createEvent("MouseEvent");c.initMouseEvent(a,!0,!0,window,1,b.screenX,b.screenY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);b.target.dispatchEvent(c)}var c=a.changedTouches,e=c[0],d=this;a.clientX=c[0].clientX;a.clientY=c[0].clientY;switch(a.type){case "touchstart":d.tstate=e;d.startx=a.clientX;d.starty=a.clientY;setTimeout(function(){null==d.tstate||d.moving||(d.cMenu=!0,b("contextmenu",d.tstate),d.tstate=null)},800);break;case "touchmove":d.moving||
(10<a.clientX-d.startx||-10>a.clientX-d.startx||10<a.clientY-d.starty||-10>a.clientY-d.starty?(d.moving=!0,d.tstate=null):cancelBubble());break;case "touchend":d.cMenu||d.moving||(b("mouseup",e),b("click",e)),d.cMenu=!1,d.tstate=null,d.moving=!1}};var gnLastEventId=0,KAMAP_ERROR=gnLastEventId++,KAMAP_WARNING=gnLastEventId++,KAMAP_NOTICE=gnLastEventId++,KAMAP_INITIALIZED=gnLastEventId++,KAMAP_MAP_INITIALIZED=gnLastEventId++,KAMAP_EXTENTS_CHANGED=gnLastEventId++,KAMAP_SCALE_CHANGED=gnLastEventId++,KAMAP_LAYERS_CHANGED=gnLastEventId++,KAMAP_LAYER_STATUS_CHANGED=gnLastEventId++,KAMAP_CONTEXT_MENU=gnLastEventId++,KAMAP_METAEXTENTS_CHANGED=gnLastEventId++,KAMAP_MAP_CLICKED=gnLastEventId++,KAMAP_MOVE_START=gnLastEventId++,KAMAP_MOVE_END=gnLastEventId++;
function kaMap(a){this.szID=a;this.domObj=this.getRawObject(a);this.domObj.style.overflow="hidden";this.initializationState=0;this.theInsideLayer=null;this.aMaps=[];this.currentMap="";this.eventManager=new _eventManager;this.server=this.server=server_url?server_url:"";this.aObjects=[];this.aCanvases=[];this.aTools=[];this.aInfoTools=[];for(a=0;a<gnLastEventId;a++)this.registerEventID(a);this.thandler=new touchHandler;this.createLayers();this.prevProj=null;this.prevScale=0;this.prevGda=1;this.llProjection=
"EPSG:4326";if(!isMobileApp){a=document.createElement("div");a.style.width="1in";var b=document.getElementsByTagName("body")[0];b.appendChild(a);var c=document.defaultView.getComputedStyle(a,null).getPropertyValue("width");b.removeChild(a);OpenLayers.DOTS_PER_INCH=parseFloat(c)}}kaMap.prototype.getMapProjection=function(){return this.olMap.getProjectionObject()};kaMap.prototype.getResolution=function(){return this.olMap.getResolution()};
kaMap.prototype.initialize=function(){var a=this;if(2==a.initializationState)return a.triggerEvent(KAMAP_ERROR,"ERROR: ka-Map! is already initialized!"),!1;if(1==a.intializationState)return a.triggerEvent(KAMAP_WARNING,"WARNING: ka-Map! is currently initializing ... wait for the KAMAP_INITIALIZED event to be triggered."),!1;a.utmProjection=utm_projection;setTimeout(function(){a.initializeOL()},50);a.initializationState=1;return!0};
kaMap.prototype.initializeOL=function(){function a(){b.getBaseLayer().gray?$("#canvasBG").css("opacity",b.getBaseLayer().gray):$("#canvasBG").css("opacity","0.33")}var b=this;b.olMap=new OpenLayers.Map({projection:utm_projection,units:"m",numZoomLevels:max_zoomlevels,zoomMethod:null,maxExtent:new OpenLayers.Bounds(max_extent[0],max_extent[1],max_extent[2],max_extent[3]),maxResolution:max_resolution,minResolution:min_resolution,controls:[new OpenLayers.Control.Navigation,new OpenLayers.Control.Attribution]});
b.addLayers();if(null!=mapViews)for(var c=0;c<mapViews.length;c++){var e=new View(mapViews[c]);b.aMaps[e.name]=e}b.olMap.getViewport().appendChild(b.theInsideLayer);b.domObj.style.overflow="hidden";b.viewportWidth=b.getObjectWidth(b.domObj);b.viewportHeight=b.getObjectHeight(b.domObj);b.setBackgroundColor(backgroundColor);b.triggerEvent(KAMAP_MAP_INITIALIZED);b.olMap.events.register("changebaselayer",b,function(){var c=this.olMap.getCenter();null!=c&&(c=c.transform(this.prevProj,this.getMapProjection()),
b.olMap.setCenter(c),c=this.geodeticAdjustment(),1>c&&1==b.prevGda?b.zoomToScale(b.olMap.getScale()/(1.4*c),!0):1>b.prevGda&1==c&&b.zoomToScale(b.olMap.getScale()*(b.prevGda/1.4),!0),this.prevProj=this.getMapProjection(),this.prevGda=c,a(),b.triggerEvent(KAMAP_LAYERS_CHANGED),b.triggerEvent(KAMAP_SCALE_CHANGED,this.getCurrentScale()))});b.olMap.events.register("zoomend",b,function(){OpenLayers.Console.info("ZOOM END: scale=",this.getCurrentScale());this.prevScale=this.getCurrentScale();b.triggerEvent(KAMAP_SCALE_CHANGED,
this.prevScale);b.triggerEvent(KAMAP_EXTENTS_CHANGED,this.getGeoExtents())});b.olMap.events.register("moveend",b,function(){mousetrack_suspend=!1;b.triggerEvent(KAMAP_EXTENTS_CHANGED,b.getGeoExtents());b.triggerEvent(KAMAP_MOVE_END)});b.olMap.events.register("movestart",b,function(){mousetrack_suspend=!0;b.triggerEvent(KAMAP_MOVE_START)});isMobile||b.olMap.addControl(new OpenLayers.Control.PanZoomBar);b.plink=new OpenLayers.Control.Permalink;b.plink.setMap(b.olMap);document.getElementById("permolink").appendChild(this.plink.draw());
b.plink.element.innerHTML="link to this view";b.olMap.render(b.domObj);b.prevScale=b.getCurrentScale();b.prevProj=b.getMapProjection();setTimeout(a,100);b.triggerEvent(KAMAP_INITIALIZED);b.triggerEvent(KAMAP_SCALE_CHANGED,b.getCurrentScale());b.initializationState=2};kaMap.prototype.addLayers=function(){if(null!=mapLayers&&0<mapLayers.length)for(var a=0;a<mapLayers.length;a++)this.olMap.addLayer(mapLayers[a].layer)};
kaMap.prototype.setBackgroundColor=function(a){this.domObj.style.backgroundColor=a;return!0};
kaMap.prototype.createLayers=function(){var a=this;this.theInsideLayer=document.createElement("div");this.theInsideLayer.id="theInsideLayer";this.theInsideLayer.style.position="absolute";this.theInsideLayer.style.left="0px";this.theInsideLayer.style.top="0px";this.theInsideLayer.style.zIndex="750";this.theInsideLayer.kaMap=this;this.currentTool&&(this.theInsideLayer.style.cursor=this.currentTool.cursor);this.domObj.kaMap=this;this.theInsideLayer.onclick=function(b){a.onclick(b)};this.theInsideLayer.onmousedown=
function(b){a.onmousedown(b)};this.theInsideLayer.onmouseup=function(b){a.onmouseup(b)};this.theInsideLayer.onmousemove=function(b){a.onmousemove(b)};this.theInsideLayer.onmouseover=function(b){a.onmouseover(b)};this.domObj.onmouseout=function(b){a.onmouseout(b)};this.theInsideLayer.onkeypress=function(b){a.onkeypress(b)};this.theInsideLayer.ondblclick=function(b){a.ondblclick(b)};this.theInsideLayer.oncontextmenu=function(b){a.oncontextmenu(b)};this.theInsideLayer.onmousewheel=function(b){a.onmousewheel(b)};
this.theInsideLayer.ontouchstart=function(b){a.thandler.handle(b);a.onmousedown(b)};this.theInsideLayer.ontouchmove=function(b){a.thandler.handle(b);a.onmousemove(b)};this.theInsideLayer.ontouchend=function(b){a.thandler.handle(b);a.onmouseup(b)};this.theInsideLayer.ontouchcancel=function(b){a.thandler.handle(b)};window.addEventListener&&this.domObj.addEventListener("DOMMouseScroll",function(b){a.onmousewheel(b)},!1);this.olMap=null};
kaMap.prototype.getRawObject=function(a){return"string"==typeof a?document.getElementById(a):a};kaMap.prototype.getObjectWidth=function(a){a=this.getRawObject(a);var b=0;a.offsetWidth?b=a.offsetWidth:a.clip&&a.clip.width?b=a.clip.width:a.style&&a.style.pixelWidth&&(b=a.style.pixelWidth);return parseInt(b)};
kaMap.prototype.getObjectHeight=function(a){a=this.getRawObject(a);var b=0;a.offsetHeight?b=a.offsetHeight:a.clip&&a.clip.height?b=a.clip.height:a.style&&a.style.pixelHeight&&(b=a.style.pixelHeight);return parseInt(b)};kaMap.prototype.zoomTo=function(a,b){var c=new OpenLayers.LonLat(a,b);c.transform(this.llProjection,this.getMapProjection());this.olMap.setCenter(c)};kaMap.prototype.zoomToPix=function(a,b,c){a=this.pixToGeo(a,b-5);this.zoomToGeo(a[0],a[1],c)};
kaMap.prototype.zoomToGeo=function(a,b,c){var e=this.getGeoExtents(),d=e[0],f=e[1],k=(e[2]-e[0])/2,e=(e[3]-e[1])/2;c||(c=.05);var n=k*c;c*=e;(a<d+k-n||a>d+k+n||b<f+e-c||b>f+e+c)&&this.zoomTo(a,b)};kaMap.prototype.zoomToExtents=function(a,b,c,e){a=new OpenLayers.Bounds(a,b,c,e);a.transform(this.llProjection,this.getMapProjection());this.olMap.zoomToExtent(a,!0)};kaMap.prototype.getExtent=function(){return this.olMap.getExtent()};
kaMap.prototype.getCenter=function(){return this.olMap.getCenter().transform(this.getMapProjection(),this.llProjection)};
kaMap.prototype.createDrawingCanvas=function(a,b){var c=document.createElement("div");c.style.position="absolute";c.id="canvas";c.style.left="0px";c.style.top="0px";c.style.zIndex=a;this.theInsideLayer.appendChild(c);c.style.width="1px";c.style.height="1px";if(b){var e=document.createElement("div");e.id="canvasBG";c.appendChild(e);e.style.marginLeft="-100px";e.style.marginTop="-100px";e.style.width="3000px";e.style.height="3000px"}this.aCanvases.push(c);c.kaMap=this;return c};
kaMap.prototype.removeDrawingCanvas=function(a){for(var b=0;b<this.aCanvases.length;b++)this.aCanvases[b]==a&&this.aCanvases.splice(b,1);this.theInsideLayer.removeChild(a);a.kaMap=null;return!0};kaMap.prototype.addObjectGeo=function(a,b,c,e){e.lon=b;e.lat=c;e.style.position="absolute";e.canvas=a;a.appendChild(e);this.aObjects.push(e)};
kaMap.prototype.removeObject=function(a){if(null==a){for(var b=0;b<this.aObjects.length;b++)a=this.aObjects[b],a.canvas&&a.canvas.removeChild(a);this.aObjects=[];return!0}for(b=0;b<this.aObjects.length;b++)if(this.aObjects[b]==a)return a=this.aObjects[b],a.canvas&&(a.canvas.removeChild(a),a.canvas=null),this.aObjects.splice(b,1),!0;return!1};
kaMap.prototype.removeAllObjects=function(a){for(var b=0;b<this.aObjects.length;b++)obj=this.aObjects[b],obj.canvas&&obj.canvas==a&&(obj.canvas.removeChild(obj),obj.canvas=null,this.aObjects.splice(b--,1));return!0};
kaMap.prototype.centerObject=function(a){var b=-safeParseInt(this.theInsideLayer.style.left)+this.viewportWidth/2,c=-safeParseInt(this.theInsideLayer.style.top)+this.viewportHeight/2,e=a.xOffset?a.xOffset:0,d=a.yOffset?a.yOffset:0,b=safeParseInt(a.style.left)-e-b;a=safeParseInt(a.style.top)-d-c;this.slideBy(-b,-a);return!0};
kaMap.prototype.updateObjects=function(){for(var a=0;a<this.aObjects.length;a++){var b=this.aObjects[a],c=b.xOffset?b.xOffset:0,e=b.yOffset?b.yOffset:0,d=this.geoToPix(b.lon,b.lat),c=d[0]+c;b.style.top=d[1]+e+"px";b.style.left=c+"px"}};kaMap.prototype.geoToPix=function(a,b){var c=new OpenLayers.LonLat(a,b),c=c.transform(this.llProjection,this.getMapProjection()),c=this.olMap.getViewPortPxFromLonLat(c);return[Math.floor(c.x),Math.floor(c.y)]};
kaMap.prototype.pixToGeo=function(a,b){3==arguments.length&&arguments[2]&&(a+=this.xOrigin,b+=this.yOrigin);var c=this.olMap.getLonLatFromPixel(new OpenLayers.Pixel(a,b)),c=c.transform(this.getMapProjection(),this.llProjection);return[c.lon,c.lat]};kaMap.prototype.drawPage=function(){var a=this.domObj,b=getInsideWindowHeight(),c=getInsideWindowWidth();a.style.width=c+"px";a.style.height=b+"px";this.olMap&&(this.olMap.updateSize(),this.triggerEvent(KAMAP_EXTENTS_CHANGED,this.getGeoExtents()))};
kaMap.prototype.onkeypress=function(a){if(this.currentTool)this.currentTool.onkeypress(a);if(0<this.aInfoTools.length)for(var b=0;b<this.aInfoTools.length;b++)this.aInfoTools[b].onkeypress(a)};kaMap.prototype.onmousemove=function(a){a=a?a:event?event:null;2==a.button&&this.triggerEvent(KAMAP_CONTEXT_MENU);if(this.currentTool)this.currentTool.onmousemove(a);if(0<this.aInfoTools.length)for(var b=0;b<this.aInfoTools.length;b++)this.aInfoTools[b].onmousemove(a)};
kaMap.prototype.onmousedown=function(a){if(this.currentTool)this.currentTool.onmousedown(a);if(0<this.aInfoTools.length)for(var b=0;b<this.aInfoTools.length;b++)this.aInfoTools[b].onmousedown(a)};kaMap.prototype.onmouseup=function(a){if(this.currentTool)this.currentTool.onmouseup(a);if(0<this.aInfoTools.length)for(var b=0;b<this.aInfoTools.length;b++)this.aInfoTools[b].onmouseup(a)};
kaMap.prototype.onmouseover=function(a){if(this.currentTool)this.currentTool.onmouseover(a);if(0<this.aInfoTools.length)for(var b=0;b<this.aInfoTools.length;b++)this.aInfoTools[b].onmouseover(a)};kaMap.prototype.onmouseout=function(a){if(this.currentTool)this.currentTool.onmouseout(a);if(0<this.aInfoTools.length)for(var b=0;b<this.aInfoTools.length;b++)this.aInfoTools[b].onmouseout(a)};kaMap.prototype.oncontextmenu=function(a){a=a?a:event;a.preventDefault&&a.preventDefault();return!1};
kaMap.prototype.onclick=function(a){a=a?a:event;if(this.currentTool)this.currentTool.onclick(a)};kaMap.prototype.ondblclick=function(a){if(this.currentTool)this.currentTool.ondblclick(a);if(0<this.aInfoTools.length)for(var b=0;b<this.kaMap.aInfoTools.length;b++)this.aInfoTools[b].ondblclick(a)};kaMap.prototype.onmousewheel=function(a){if(this.currentTool)this.currentTool.onmousewheel(a)};
kaMap.prototype.cancelEvent=function(a){a=a?a:event?event:null;a.returnValue=!1;a.preventDefault&&a.preventDefault();return!1};kaMap.prototype.registerTool=function(a){this.aTools.push(a)};kaMap.prototype.activateTool=function(a){a.isInfoTool()?this.aInfoTools.push(a):(this.currentTool&&this.currentTool.deactivate(),this.currentTool=a,this.theInsideLayer&&this.setCursor(this.currentTool.cursor))};
kaMap.prototype.deactivateTool=function(a){if(a.isInfoTool())for(var b=0;b<this.aInfoTools.length;b++){if(this.aInfoTools[b]==a){this.aInfoTools.splice(b,1);break}}else this.currentTool==a&&(this.currentTool=null),this.theInsideLayer&&(this.theInsideLayer.style.cursor="auto")};
kaMap.prototype.setCursor=function(a){if(a&&a.length&&"object"==typeof a)for(var b=0;b<a.length&&(this.theInsideLayer.style.cursor=a[b],this.theInsideLayer.style.cursor!=a[b]);b++);else this.theInsideLayer.style.cursor="string"==typeof a?a:"auto"};kaMap.prototype.getMaps=function(){return this.aMaps};kaMap.prototype.getCurrentMap=function(){return this.aMaps[this.currentMap]};
kaMap.prototype.selectMap=function(a,b){OpenLayers.Console.info("selectMap: "+a);if(this.aMaps[a]){this.currentMap=a;if(!b){var c=this.aMaps[a];this.zoomToExtents(c.extent[0],c.extent[1],c.extent[2],c.extent[3])}return!0}OpenLayers.Console.warn("Map area not found: "+a);return!1};kaMap.prototype.getBaseLayer=function(){return this.olMap.baseLayer};kaMap.prototype.setBaseLayerId=function(a){a=this.olMap.getLayer(a);null!=a&&this.olMap.setBaseLayer(a)};kaMap.prototype.getMaxScale=function(){return 5E3};
kaMap.prototype.getUnits=function(){return this.olMap.getUnits()};kaMap.prototype.getGeoExtents=function(){var a=this.olMap.getExtent().transform(this.getMapProjection(),this.llProjection);if(null!=a)return a.toArray();OpenLayers.Console.warn("getGeoExtents: extent is null");return[0,0,0,0]};kaMap.prototype.zoomIn=function(){this.olMap.zoomIn()};kaMap.prototype.zoomOut=function(){this.olMap.zoomOut()};kaMap.prototype.zoomToScale=function(a){this.olMap.zoomToScale(a)};
kaMap.prototype.geodeticAdjustment=function(){if(/EPSG:(900913|3857|4326)/.test(this.olMap.getProjection())&&null!=this.olMap.getCenter()){var a=this.olMap.getCenter().transform(this.getMapProjection(),"EPSG:4326");return Math.cos(a.lat/180*Math.PI)}return 1};kaMap.prototype.getCurrentScale=function(){return null==this.olMap?null:this.olMap.getScale()*this.geodeticAdjustment()};kaMap.prototype.registerEventID=function(a){return this.eventManager.registerEventID(a)};
kaMap.prototype.registerForEvent=function(a,b,c){return this.eventManager.registerForEvent(a,b,c)};kaMap.prototype.deregisterForEvent=function(a,b,c){return this.eventManager.deregisterForEvent(a,b,c)};kaMap.prototype.triggerEvent=function(a){return this.eventManager.triggerEvent.apply(this.eventManager,arguments)};function safeParseInt(a){return Math.round(parseFloat(a))}
function View(a){this.name="undefined"!=typeof a.name?a.name:"noname";this.title="undefined"!=typeof a.title?a.title:"no title";this.extent="undefined"!=typeof a.extent?a.extent:[];this.hidden="undefined"!=typeof a.hidden?a.hidden:!1};var kaCurrentTool=null;function kaTool(a){this.kaMap=a;this.name="kaTool";this.bInfoTool=!1;this.wheelPlus=[a,a.zoomIn,null];this.wheelMinus=[a,a.zoomOut,null];this.kaMap.registerTool(this)}kaTool.prototype.isInfoTool=function(){return this.bInfoTool};kaTool.prototype.activate=function(){this.kaMap.activateTool(this);document.kaCurrentTool=this};kaTool.prototype.deactivate=function(){this.kaMap.deactivateTool(this);document.kaCurrentTool=null};kaTool.prototype.onmousemove=function(a){return!1};
kaTool.prototype.onmousedown=function(a){return!1};kaTool.prototype.onmouseup=function(a){return!1};kaTool.prototype.ondblclick=function(a){return!1};kaTool.prototype.setMouseWheel=function(a,b){this.wheelMinus=a;this.wheelPlus=b};kaTool.prototype.onmousewheel=function(a){a=a?a:event?event:null;var b=null;if(b=0<(a.wheelDelta?a.wheelDelta:-1*a.detail)?this.wheelPlus:this.wheelMinus)obj=b[0]?b[0]:null,func=b[1]?b[1]:null,args=b[2]?b[2]:null,func&&(args?func.apply(obj,args):func.apply(obj))};
kaTool.prototype.adjustPixPosition=function(a,b){for(var c=this.kaMap.domObj,e=0,d=0;c;)e+=parseInt(c.offsetLeft),d+=parseInt(c.offsetTop),c=c.offsetParent;c=parseInt(this.kaMap.theInsideLayer.style.left)+e-a;d=parseInt(this.kaMap.theInsideLayer.style.top)+d-b;return[c,d]};function kaTool_redirect_onkeypress(a){if(document.kaCurrentTool)document.kaCurrentTool.onkeypress(a)}
kaTool.prototype.onkeypress=function(a){if(a=a?a:event?event:null){var b=!0;switch(a.charCode?a.charCode:a.keyCode){case 38:this.kaMap.moveBy(0,16);this.kaMap.triggerEvent(KAMAP_EXTENTS_CHANGED,this.kaMap.getGeoExtents());break;case 40:this.kaMap.moveBy(0,-16);this.kaMap.triggerEvent(KAMAP_EXTENTS_CHANGED,this.kaMap.getGeoExtents());break;case 37:this.kaMap.moveBy(16,0);this.kaMap.triggerEvent(KAMAP_EXTENTS_CHANGED,this.kaMap.getGeoExtents());break;case 39:this.kaMap.moveBy(-16,0);this.kaMap.triggerEvent(KAMAP_EXTENTS_CHANGED,
this.kaMap.getGeoExtents());break;case 33:this.kaMap.slideBy(0,this.kaMap.viewportHeight/2);break;case 34:this.kaMap.slideBy(0,-this.kaMap.viewportHeight/2);break;case 36:this.kaMap.slideBy(this.kaMap.viewportWidth/2,0);break;case 35:this.kaMap.slideBy(-this.kaMap.viewportWidth/2,0);break;case 43:case 61:this.kaMap.zoomIn();break;case 45:this.kaMap.zoomOut();break;default:b=!1}return b?this.cancelEvent(a):!0}};kaTool.prototype.onmouseover=function(a){return!1};
kaTool.prototype.onmouseout=function(a){this.kaMap.isIE4&&(document.onkeydown=null);document.onkeypress=null;return!1};kaTool.prototype.cancelEvent=function(a){a=a?a:event?event:null;a.cancelBubble=!0;a.returnValue=!1;a.stopPropogation&&a.stopPropogation();a.preventDefault&&a.preventDefault();return!1};
function kaNavigator(a){kaTool.apply(this,[a]);this.name="kaNavigator";this.cursor=["url('KaMap/images/grab.cur'),move","-moz-grab","grab","move"];this.activeImage=this.kaMap.server+"images/button_pan_3.png";this.disabledImage=this.kaMap.server+"images/button_pan_2.png";for(var b in kaTool.prototype)kaNavigator.prototype[b]||(kaNavigator.prototype[b]=kaTool.prototype[b])}kaNavigator.prototype.onmouseout=null;kaNavigator.prototype.onmousemove=null;kaNavigator.prototype.onmousedown=null;
kaNavigator.prototype.onmouseup=null;kaNavigator.prototype.onclick=function(){return!0};var gDblClickTimer=kaNavigator.prototype.ondblclick=null;kaNavigator.prototype.dispatchMapClicked=function(a,b){var c=this.adjustPixPosition(a,b),c=this.kaMap.pixToGeo(c[0],c[1]);gDblClickTimer=null;this.kaMap.triggerEvent(KAMAP_MAP_CLICKED,c)};function bind(a,b){for(var c=arguments[0],e=arguments[1],d=[],f=2;f<arguments.length;f++)d.push(arguments[f]);return function(){return c.apply(e,d)}};var KAMAP_QUERY=gnLastEventId++,KAMAP_POINT_QUERY=0,KAMAP_RECT_QUERY=1;
function kaQuery(a,b){kaTool.apply(this,[a]);this.name="kaQuery";this.cursor="help";this.domObj=document.createElement("div");this.domObj.style.position="absolute";this.domObj.style.top="0px";this.domObj.style.left="0px";this.domObj.style.width="1px";this.domObj.style.height="1px";this.domObj.style.zIndex=100;this.domObj.style.visibility="hidden";this.domObj.style.border="1px solid red";this.domObj.style.backgroundColor="white";this.domObj.style.opacity=.5;this.domObj.style.mozOpacity=.5;this.domObj.style.filter=
"Alpha(opacity=50)";this.kaMap.theInsideLayer.appendChild(this.domObj);this.starty=this.startx=null;this.type=b;for(var c in kaTool.prototype)kaQuery.prototype[c]||(kaQuery.prototype[c]=kaTool.prototype[c])}
kaQuery.prototype.onclick=function(a){a=a?a:event?event:null;var b=KAMAP_POINT_QUERY;a=this.adjustPixPosition(a.pageX||a.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft),a.pageY||a.clientY+(document.documentElement.scrollTop||document.body.scrollTop));this.startx=-a[0];this.starty=-a[1];a=this.kaMap.pixToGeo(this.startx,this.starty);this.kaMap.triggerEvent(KAMAP_QUERY,b,a);return!1};var KAMAP_MOUSE_TRACKER=gnLastEventId++,mousetrack_suspend=!1;function kaMouseTracker(a){kaTool.apply(this,[a]);this.name="kaMouseTracker";this.bInfoTool=!0;for(var b in kaTool.prototype)kaMouseTracker.prototype[b]||(kaMouseTracker.prototype[b]=kaTool.prototype[b])}
kaMouseTracker.prototype.onmousemove=function(a){a=a?a:event?event:null;if(mousetrack_suspend)return!1;a=this.kaMap.pixToGeo(a.pageX||a.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft),a.pageY||a.clientY+(document.documentElement.scrollTop||document.body.scrollTop));this.kaMap.triggerEvent(KAMAP_MOUSE_TRACKER,{x:a[0],y:a[1]});return!1};function ScaleBar(a){this.scaleDenominator=null==a?1:a;this.displaySystem="metric";this.minWidth=100;this.maxWidth=200;this.subdivisions=this.divisions=2;this.singleLine=this.abbreviateLabel=this.showMinorMeasures=!1;this.resolution=OpenLayers.DOTS_PER_INCH;this.align="center";this.container=document.createElement("div");this.container.className="sbWrapper";this.labelContainer=document.createElement("div");this.labelContainer.className="sbUnitsContainer";this.labelContainer.style.position="absolute";
this.graphicsContainer=document.createElement("div");this.graphicsContainer.style.position="absolute";this.graphicsContainer.className="sbGraphicsContainer";this.numbersContainer=document.createElement("div");this.numbersContainer.style.position="absolute";this.numbersContainer.className="sbNumbersContainer";a=document.createElement("div");a.className="sbMarkerMajor";this.graphicsContainer.appendChild(a);a=document.createElement("div");a.className="sbMarkerMinor";this.graphicsContainer.appendChild(a);
a=document.createElement("div");a.className="sbBar";this.graphicsContainer.appendChild(a);a=document.createElement("div");a.className="sbBarAlt";this.graphicsContainer.appendChild(a)}
ScaleBar.prototype.update=function(a){function b(a,b,c){c=null==c?10:c;for(var e=Number.POSITIVE_INFINITY,d=Number.POSITIVE_INFINITY,f=a,g=3,h=0;3>h;++h)for(var k=Math.pow(2,-1*h),l=Math.floor(Math.log(b/k)/Math.LN10),m=l;m>l-c+1;--m){var n=Math.max(h-m,0),p=k*Math.pow(10,m);if(p*Math.floor(b/p)>=a){var r=0==a%p?a/p:Math.floor(a/p)+1,q=r+2*h,t=0>m?Math.abs(m)+1:m;if(q<e||q==e&&t<d)e=q,d=t,f=(p*r).toFixed(n),g=n}}this.value=f;this.score=e;this.tieBreaker=d;this.numDec=g}function c(a,b){var c=0;if(document.styleSheets)for(var e=
document.styleSheets.length-1;0<=e;--e){var d=document.styleSheets[e];if(!d.disabled){if("undefined"==typeof d.cssrules){if("undefined"==typeof d.rules)return 0;d=d.rules}else d=d.cssRules;if(d)for(var f=0;f<d.length;++f){var g=d[f];g.selectorText&&g.selectorText.toLowerCase()==a.toLowerCase()&&""!=g.style[b]&&(c=parseInt(g.style[b]))}}}return c?c:0}null!=a&&(this.scaleDenominator=a);b.prototype.toString=function(){return this.value.toString()};b.prototype.valueOf=function(){return this.value};this.container.title=
"scale 1:"+function(a,b){b=b?b:0;for(var c=""+Math.round(a),d=/(-?[0-9]+)([0-9]{3})/;d.test(c);)c=c.replace(d,"$1,$2");return 0<b?(d=Math.floor(Math.pow(10,b)*(a-Math.round(a))),0==d?c:c+"."+d):c}(this.scaleDenominator);for(var e={english:{units:["miles","feet","inches"],abbr:["mi","ft","in"],inches:[63360,12,1]},metric:{units:["kilometers","meters","centimeters"],abbr:["km","m","cm"],inches:[39370.07874,39.370079,.393701]}},d=[],f=0;f<e[this.displaySystem].units.length;++f){d[f]={};var k=this.resolution*
e[this.displaySystem].inches[f]/this.scaleDenominator;a=this.minWidth/k/(this.divisions*this.subdivisions);for(var n=this.maxWidth/k/(this.divisions*this.subdivisions),h=0;h<this.divisions*this.subdivisions;++h){k=new b(a*(h+1),n*(h+1));d[f][h]={value:k.value/(h+1),score:0,tieBreaker:0,numDec:0,displayed:0};for(var l=0;l<this.divisions*this.subdivisions;++l){displayedValuePosition=k.value*(l+1)/(h+1);niceNumber2=new b(displayedValuePosition,displayedValuePosition);var p=0==(l+1)%this.subdivisions,
r=l+1==this.divisions*this.subdivisions;this.singleLine&&r||!this.singleLine&&(p||this.showMinorMeasures)?(d[f][h].score+=niceNumber2.score,d[f][h].tieBreaker+=niceNumber2.tieBreaker,d[f][h].numDec=Math.max(d[f][h].numDec,niceNumber2.numDec),d[f][h].displayed+=1):(d[f][h].score+=niceNumber2.score/this.subdivisions,d[f][h].tieBreaker+=niceNumber2.tieBreaker/this.subdivisions)}d[f][h].score*=(f+1)*d[f][h].tieBreaker/d[f][h].displayed}}for(var k=n=a=l=null,u=r=Number.POSITIVE_INFINITY,f=p=0;f<d.length;++f)for(h in d[f])if(d[f][h].score<
r||d[f][h].score==r&&d[f][h].tieBreaker<u)r=d[f][h].score,u=d[f][h].tieBreaker,l=d[f][h].value,p=d[f][h].numDec,a=e[this.displaySystem].units[f],n=e[this.displaySystem].abbr[f],k=this.resolution*e[this.displaySystem].inches[f]/this.scaleDenominator,k*=l;d=(c(".sbMarkerMajor","borderLeftWidth")+c(".sbMarkerMajor","width")+c(".sbMarkerMajor","borderRightWidth"))/2;f=(c(".sbMarkerMinor","borderLeftWidth")+c(".sbMarkerMinor","width")+c(".sbMarkerMinor","borderRightWidth"))/2;r=(c(".sbBar","borderLeftWidth")+
c(".sbBar","borderRightWidth"))/2;u=(c(".sbBarAlt","borderLeftWidth")+c(".sbBarAlt","borderRightWidth"))/2;document.styleSheets||(f=d=.5);for(;this.labelContainer.hasChildNodes();)this.labelContainer.removeChild(this.labelContainer.firstChild);for(;this.graphicsContainer.hasChildNodes();)this.graphicsContainer.removeChild(this.graphicsContainer.firstChild);for(;this.numbersContainer.hasChildNodes();)this.numbersContainer.removeChild(this.numbersContainer.firstChild);for(var g,m,h={left:0,center:-1*
this.divisions*this.subdivisions*k/2,right:-1*this.divisions*this.subdivisions*k},e=0+h[this.align],q=m=0;q<this.divisions;++q){e=q*this.subdivisions*k;e+=h[this.align];m=0==q?0:(q*this.subdivisions*l).toFixed(p);g=document.createElement("div");g.className="sbMarkerMajor";g.style.position="absolute";g.style.overflow="hidden";g.style.left=Math.round(e-d)+"px";g.appendChild(document.createTextNode(" "));this.graphicsContainer.appendChild(g);this.singleLine||(g=document.createElement("div"),g.className=
"sbNumbersBox",g.style.position="absolute",g.style.overflow="hidden",g.style.textAlign="center",this.showMinorMeasures?(g.style.width=Math.round(2*k)+"px",g.style.left=Math.round(e-k)+"px"):(g.style.width=Math.round(this.subdivisions*k*2)+"px",g.style.left=Math.round(e-this.subdivisions*k)+"px"),g.appendChild(document.createTextNode(m)),this.numbersContainer.appendChild(g));for(var t=0;t<this.subdivisions;++t)m=document.createElement("div"),m.style.position="absolute",m.style.overflow="hidden",m.style.width=
Math.round(k)+"px",0==t%2?(m.className="sbBar",m.style.left=Math.round(e-r)+"px"):(m.className="sbBarAlt",m.style.left=Math.round(e-u)+"px"),m.appendChild(document.createTextNode(" ")),this.graphicsContainer.appendChild(m),t<this.subdivisions-1&&(e=(q*this.subdivisions+(t+1))*k,e+=h[this.align],m=(q*this.subdivisions+t+1)*l,g=document.createElement("div"),g.className="sbMarkerMinor",g.style.position="absolute",g.style.overflow="hidden",g.style.left=Math.round(e-f)+"px",g.appendChild(document.createTextNode(" ")),
this.graphicsContainer.appendChild(g),this.showMinorMeasures&&!this.singleLine&&(g=document.createElement("div"),g.className="sbNumbersBox",g.style.position="absolute",g.style.overflow="hidden",g.style.textAlign="center",g.style.width=Math.round(2*k)+"px",g.style.left=Math.round(e-k)+"px",g.appendChild(document.createTextNode(m)),this.numbersContainer.appendChild(g)))}e=this.divisions*this.subdivisions*k;e+=h[this.align];m=(this.divisions*this.subdivisions*l).toFixed(p);g=document.createElement("div");
g.className="sbMarkerMajor";g.style.position="absolute";g.style.overflow="hidden";g.style.left=Math.round(e-d)+"px";g.appendChild(document.createTextNode(" "));this.graphicsContainer.appendChild(g);this.singleLine||(g=document.createElement("div"),g.className="sbNumbersBox",g.style.position="absolute",g.style.overflow="hidden",g.style.textAlign="center",this.showMinorMeasures?(g.style.width=Math.round(2*k)+"px",g.style.left=Math.round(e-k)+"px"):(g.style.width=Math.round(this.subdivisions*k*2)+"px",
g.style.left=Math.round(e-this.subdivisions*k)+"px"),g.appendChild(document.createTextNode(m)),this.numbersContainer.appendChild(g));l=document.createElement("div");l.style.position="absolute";this.singleLine?(p=m,l.className="sbLabelBoxSingleLine",l.style.top="-0.6em",l.style.left=e+10+"px"):(p="",l.className="sbLabelBox",l.style.textAlign="center",l.style.width=Math.round(this.divisions*this.subdivisions*k)+"px",l.style.left=Math.round(h[this.align])+"px",l.style.overflow="hidden");p=this.abbreviateLabel?
p+(" "+n):p+(" "+a);l.appendChild(document.createTextNode(p));this.labelContainer.appendChild(l);document.styleSheets||(a=document.createElement("style"),a.type="text/css",n=".sbBar {top: 0px; background: #666666; height: 1px; border: 0;}.sbBarAlt {top: 0px; background: #666666; height: 1px; border: 0;}.sbMarkerMajor {height: 7px; width: 1px; background: #666666; border: 0;}",n+=".sbMarkerMinor {height: 5px; width: 1px; background: #666666; border: 0;}",n+=".sbLabelBox {top: -16px;}",n+=".sbNumbersBox {top: 7px;}",
a.appendChild(document.createTextNode(n)),document.getElementsByTagName("head").item(0).appendChild(a));this.container.appendChild(this.graphicsContainer);this.container.appendChild(this.labelContainer);this.container.appendChild(this.numbersContainer)};ScaleBar.prototype.place=function(a){null==a?document.body.appendChild(this.container):(a=document.getElementById(a),null!=a&&a.appendChild(this.container));this.update()};
